import express from 'express'
import multer from 'multer'
import path from 'node:path'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { createHash, randomUUID } from 'node:crypto'
import { config } from './config.js'
import { closeDatabase, pool, transaction } from './db.js'
import { decryptDocument, encryptDocument, hashPassword, randomToken, sha256, verifyPassword } from './security.js'
import { normalizeTranslationAssessment, translationApprovalIssues, translationProposalIssues } from './review-policy.js'
import { validateAtlas } from '../src/data/validate.js'
import { atlasData } from '../src/data/atlas.js'

config.assertProductionSecrets()
const app=express()
if(config.trustProxy)app.set('trust proxy',1)
app.disable('x-powered-by')
app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"});next()})
app.use(express.json({limit:'12mb'}))

const allowedOrigins=new Set([config.appOrigin])
app.use('/api',(req,res,next)=>{if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const origin=req.get('origin');if(origin&&!allowedOrigins.has(origin))return res.status(403).json({error:'Origin is not allowed.'});next()})

const attempts=new Map()
const rateLimit=(bucket,max,windowMs)=>(req,res,next)=>{const key=`${bucket}:${req.ip}`;const now=Date.now();const entry=attempts.get(key);if(!entry||entry.until<now){attempts.set(key,{count:1,until:now+windowMs});return next()}if(entry.count>=max)return res.status(429).json({error:'Too many attempts. Please try again later.'});entry.count+=1;next()}
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(value=>value.trim().split(/=(.*)/s)).filter(parts=>parts[0]).map(([key,value])=>[decodeURIComponent(key),decodeURIComponent(value||'')]))
const clean=(value,max=255)=>typeof value==='string'?value.trim().slice(0,max):''
const email=value=>clean(value,254).toLowerCase()
const safeJson=value=>{try{return typeof value==='string'?JSON.parse(value):value}catch{return null}}
const rolesFor=async(db,userId)=>(await db.query('SELECT role FROM user_roles WHERE user_id=?',[userId])).map(row=>row.role)
const publicUser=(row,roles,karma=0)=>({id:row.id,email:row.email,displayName:row.display_name,displayNameKn:row.display_name_kn,preferredLocale:row.preferred_locale,profession:row.profession,professionDetails:row.profession_details,affiliationType:row.affiliation_type,institutionName:row.institution_name,institutionUrl:row.institution_url,publicBio:row.public_bio,accountStatus:row.account_status,verifiedBadge:Boolean(row.verified_badge),roles,canExport:row.account_status==='approved'&&roles.some(role=>['exporter','administrator'].includes(role)),karma:Number(karma||0)})
const audit=async(db,actor,action,entityType,entityId,metadata={})=>db.query('INSERT INTO audit_log (id,actor_user_id,action,entity_type,entity_id,metadata_json) VALUES (?,?,?,?,?,?)',[randomUUID(),actor||null,action,entityType,entityId||null,JSON.stringify(metadata)])

async function loadSession(req,res,next){
  const token=cookies(req).kha_session;if(!token)return next()
  const rows=await pool.query(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>UTC_TIMESTAMP(3) LIMIT 1`,[sha256(token)])
  if(!rows.length){res.clearCookie('kha_session',{path:'/'});return next()}
  req.user=rows[0];req.roles=await rolesFor(pool,rows[0].id);next()
}
app.use('/api',loadSession)
const requireUser=(req,res,next)=>req.user?next():res.status(401).json({error:'Sign in is required.'})
const requireApproved=(req,res,next)=>req.user?.account_status==='approved'?next():res.status(403).json({error:'Sanchaya approval is required before contributing.'})
const requireRole=(...roles)=>(req,res,next)=>roles.some(role=>req.roles?.includes(role))?next():res.status(403).json({error:'This action requires an appointed role.'})
const datasetContent=value=>`${JSON.stringify(value,null,2)}\n`
const datasetIssues=value=>validateAtlas(value).filter(issue=>issue.severity==='error')

app.get('/api/health',async(req,res)=>{await pool.query('SELECT 1');res.json({ok:true,service:'Karnataka Historical Atlas community API'})})

app.post('/api/auth/register',rateLimit('register',8,60*60*1000),async(req,res)=>{
  const body=req.body||{};const userEmail=email(body.email);const displayName=clean(body.displayName,160);const profession=clean(body.profession,80)
  if(!userEmail.includes('@')||!displayName||!profession)return res.status(400).json({error:'Name, email and profession are required.'})
  if(body.acceptTerms!==true||body.acceptPrivacy!==true)return res.status(400).json({error:'Terms and privacy consent are required.'})
  const passwordHash=await hashPassword(body.password);const id=randomUUID();const now=new Date()
  try{await transaction(async db=>{await db.query(`INSERT INTO users (id,email,password_hash,display_name,display_name_kn,preferred_locale,profession,profession_details,affiliation_type,institution_name,institution_url,public_bio,terms_accepted_at,privacy_accepted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,userEmail,passwordHash,displayName,clean(body.displayNameKn,160)||null,body.preferredLocale==='en'?'en':'kn',profession,clean(body.professionDetails)||null,['school','college','university','research-institute','museum','government','nonprofit','other'].includes(body.affiliationType)?body.affiliationType:'none',clean(body.institutionName)||null,clean(body.institutionUrl,500)||null,clean(body.publicBio,2000)||null,now,now]);await db.query(`INSERT INTO user_roles (user_id,role) VALUES (?,'contributor')`,[id]);await audit(db,id,'account.registered','user',id,{profession,affiliationType:body.affiliationType||'none'})})}
  catch(error){if(error.code==='ER_DUP_ENTRY')return res.status(409).json({error:'An account already exists for this email.'});throw error}
  res.status(201).json({ok:true,status:'pending',message:'Account submitted for Sanchaya approval.'})
})

app.post('/api/auth/login',rateLimit('login',12,15*60*1000),async(req,res)=>{
  const rows=await pool.query('SELECT * FROM users WHERE email=? LIMIT 1',[email(req.body?.email)]);const user=rows[0]
  if(!user||!await verifyPassword(req.body?.password||'',user.password_hash))return res.status(401).json({error:'Email or password is incorrect.'})
  if(['rejected','suspended'].includes(user.account_status))return res.status(403).json({error:'This account is not available.'})
  const token=randomToken();const expires=new Date(Date.now()+config.sessionDays*86400000)
  await pool.query('INSERT INTO sessions (token_hash,user_id,expires_at,ip_hash,user_agent_hash) VALUES (?,?,?,?,?)',[sha256(token),user.id,expires,sha256(req.ip||''),sha256(req.get('user-agent')||'')])
  res.cookie('kha_session',token,{httpOnly:true,secure:config.env==='production',sameSite:'lax',path:'/',maxAge:config.sessionDays*86400000})
  const roles=await rolesFor(pool,user.id);res.json({user:publicUser(user,roles)})
})
app.post('/api/auth/logout',requireUser,async(req,res)=>{const token=cookies(req).kha_session;if(token)await pool.query('DELETE FROM sessions WHERE token_hash=?',[sha256(token)]);res.clearCookie('kha_session',{path:'/'});res.json({ok:true})})
app.get('/api/auth/me',requireUser,async(req,res)=>{const rows=await pool.query('SELECT COALESCE(SUM(points),0) karma FROM karma_ledger WHERE user_id=?',[req.user.id]);res.json({user:publicUser(req.user,req.roles,rows[0]?.karma)})})
app.put('/api/auth/profile',requireUser,async(req,res)=>{
  const body=req.body||{}
  const displayName=clean(body.displayName,160),displayNameKn=clean(body.displayNameKn,160)||null,profession=clean(body.profession,80)
  const affiliationType=['none','school','college','university','research-institute','museum','government','nonprofit','other'].includes(body.affiliationType)?body.affiliationType:'none'
  if(!displayName||!profession)return res.status(400).json({error:'Name and profession are required.'})
  await pool.query('UPDATE users SET display_name=?,display_name_kn=?,preferred_locale=?,profession=?,profession_details=?,affiliation_type=?,institution_name=?,institution_url=?,public_bio=? WHERE id=?',[displayName,displayNameKn,body.preferredLocale==='en'?'en':'kn',profession,clean(body.professionDetails,255)||null,affiliationType,clean(body.institutionName,255)||null,clean(body.institutionUrl,500)||null,clean(body.publicBio,2000)||null,req.user.id])
  await audit(pool,req.user.id,'account.profile-updated','user',req.user.id,{profession,affiliationType})
  const rows=await pool.query('SELECT COALESCE(SUM(points),0) karma FROM karma_ledger WHERE user_id=?',[req.user.id]);const userRows=await pool.query('SELECT * FROM users WHERE id=? LIMIT 1',[req.user.id])
  res.json({ok:true,user:publicUser(userRows[0],req.roles,rows[0]?.karma)})
})

app.get('/api/administration/dataset',requireUser,requireApproved,requireRole('administrator'),async(req,res)=>{
  const rows=await pool.query('SELECT revision,schema_version,content_sha256,dataset_json,updated_by,created_at FROM dataset_snapshots ORDER BY revision DESC LIMIT 1')
  if(!rows.length){
    const content=datasetContent(atlasData);const hash=createHash('sha256').update(content).digest('hex');const id=randomUUID()
    await pool.query('INSERT INTO dataset_snapshots (id,schema_version,revision,content_sha256,dataset_json,updated_by) VALUES (?,?,?,?,?,?)',[id,atlasData.meta.schemaVersion,1,hash,content,req.user.id]);await audit(pool,req.user.id,'dataset.snapshot-seeded','dataset',id,{revision:1,contentSha256:hash})
    return res.json({revision:1,schemaVersion:atlasData.meta.schemaVersion,contentSha256:hash,dataset:atlasData,updatedBy:req.user.id,updatedAt:new Date().toISOString()})
  }
  const row=rows[0];res.json({revision:Number(row.revision),schemaVersion:row.schema_version,contentSha256:row.content_sha256,dataset:safeJson(row.dataset_json),updatedBy:row.updated_by,updatedAt:row.created_at})
})

app.put('/api/administration/dataset',requireUser,requireApproved,requireRole('administrator'),async(req,res)=>{
  const dataset=req.body?.dataset;const baseRevision=Number(req.body?.baseRevision||0);if(!dataset||typeof dataset!=='object'||Array.isArray(dataset))return res.status(400).json({error:'A complete atlas dataset object is required.'})
  const issues=datasetIssues(dataset);if(issues.length)return res.status(422).json({error:`Dataset has ${issues.length} validation error(s).`,issues})
  const content=datasetContent(dataset);const hash=createHash('sha256').update(content).digest('hex')
  const result=await transaction(async db=>{
    const latest=(await db.query('SELECT revision FROM dataset_snapshots ORDER BY revision DESC LIMIT 1 FOR UPDATE'))[0];const currentRevision=Number(latest?.revision||0);if(currentRevision!==baseRevision)throw Object.assign(new Error(`Dataset changed on the server. Reload revision ${currentRevision} before saving.`),{status:409})
    const revision=currentRevision+1;const id=randomUUID();await db.query('INSERT INTO dataset_snapshots (id,schema_version,revision,content_sha256,dataset_json,updated_by) VALUES (?,?,?,?,?,?)',[id,dataset.meta?.schemaVersion||'unknown',revision,hash,content,req.user.id]);await audit(db,req.user.id,'dataset.snapshot-created','dataset',id,{revision,contentSha256:hash});return {id,revision}
  })
  res.status(201).json({ok:true,...result,contentSha256:hash})
})

app.get('/api/evidence/assignments',requireUser,requireApproved,async(req,res)=>{
  const rows=await pool.query('SELECT task_id,status,assignee,due_date,updated_by,updated_at FROM evidence_assignments ORDER BY updated_at DESC')
  res.json({assignments:rows.map(row=>({taskId:row.task_id,status:row.status,assignee:row.assignee||'',due:row.due_date?String(row.due_date).slice(0,10):'',updatedBy:row.updated_by,updatedAt:row.updated_at}))})
})

app.put('/api/evidence/assignments/:taskId',requireUser,requireApproved,async(req,res)=>{
  const taskId=clean(req.params.taskId,240);const status=req.body?.status;const assignee=clean(req.body?.assignee,255)||null;const due=clean(req.body?.due,10)||null
  if(!taskId||!/^[^/]+$/.test(taskId))return res.status(400).json({error:'A valid evidence task ID is required.'})
  if(!['todo','in-progress','awaiting-review','blocked','complete'].includes(status))return res.status(400).json({error:'Evidence task status is invalid.'})
  if(due&&!/^\d{4}-\d{2}-\d{2}$/.test(due))return res.status(400).json({error:'Due date must use YYYY-MM-DD.'})
  await transaction(async db=>{await db.query(`INSERT INTO evidence_assignments (task_id,status,assignee,due_date,updated_by) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),assignee=VALUES(assignee),due_date=VALUES(due_date),updated_by=VALUES(updated_by),updated_at=CURRENT_TIMESTAMP(3)`,[taskId,status,assignee,due,req.user.id]);await audit(db,req.user.id,'evidence-assignment.updated','evidence-task',taskId,{status,assignee,due})})
  res.json({ok:true,taskId,status,assignee:assignee||'',due:due||''})
})

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1,fields:5,parts:6},fileFilter:(req,file,callback)=>callback(null,['image/jpeg','image/png','application/pdf'].includes(file.mimetype))})
app.post('/api/verification-requests',requireUser,upload.single('institutionId'),async(req,res)=>{
  if(!req.file)return res.status(400).json({error:'A JPEG, PNG or PDF institution ID is required.'})
  if(!config.documentEncryptionKey)return res.status(503).json({error:'Private document storage is not configured.'})
  const institutionName=clean(req.body.institutionName,255);if(!institutionName)return res.status(400).json({error:'Institution name is required.'})
  const existing=await pool.query(`SELECT id FROM verification_requests WHERE user_id=? AND status='pending' LIMIT 1`,[req.user.id]);if(existing.length)return res.status(409).json({error:'A verification request is already pending.'})
  await mkdir(config.uploadDir,{recursive:true,mode:0o700});const id=randomUUID();const storageKey=`${id}.enc`;await writeFile(path.join(config.uploadDir,storageKey),encryptDocument(req.file.buffer,config.documentEncryptionKey),{mode:0o600})
  await pool.query(`INSERT INTO verification_requests (id,user_id,institution_name,institutional_identifier,document_storage_key,document_mime,document_sha256,document_size) VALUES (?,?,?,?,?,?,?,?)`,[id,req.user.id,institutionName,clean(req.body.institutionalIdentifier,120)||null,storageKey,req.file.mimetype,sha256(req.file.buffer),req.file.size]);await audit(pool,req.user.id,'verification.requested','verification-request',id,{institutionName});res.status(201).json({ok:true,id,status:'pending'})
})
app.get('/api/verification-requests/mine',requireUser,async(req,res)=>{const rows=await pool.query('SELECT id,institution_name,status,review_note,reviewed_at,created_at FROM verification_requests WHERE user_id=? ORDER BY created_at DESC',[req.user.id]);res.json({requests:rows})})

const normalizeContribution=body=>{const record=safeJson(body.proposedRecord);const citations=Array.isArray(body.citations)?body.citations.filter(item=>item&&typeof item.url==='string'&&/^https?:\/\//i.test(item.url)).slice(0,20).map(item=>({url:clean(item.url,1000),title:clean(item.title,255),locator:clean(item.locator,500)})):[];return {action:['create','update','correction','citation','translation'].includes(body.action)?body.action:'update',recordType:clean(body.recordType,80),targetRecordId:clean(body.targetRecordId,160)||null,title:clean(body.title,255),rationale:clean(body.rationale,10000),record,citations}}
const proposalIssues=value=>{const issues=[];if(!value.recordType||!value.title||!value.rationale||!value.record||typeof value.record!=='object'||Array.isArray(value.record))issues.push('Record type, title, rationale and a valid proposed record are required.');if(value.action==='create'&&!/^[a-z0-9]+(?:-[a-z0-9]+)+$/.test(value.record?.id||''))issues.push('New records require a stable lowercase hyphenated ID.');if(value.action!=='create'&&!value.targetRecordId)issues.push('Changes to an existing record require its stable target ID.');if(value.action==='create'&&(!value.record?.name?.kn||!value.record?.name?.en))issues.push('New records require Kannada and English names.');if(value.record?.date&&(!Number.isFinite(value.record.date.from)||!['BCE','CE'].includes(value.record.date.era)||!['exact','year','circa','range','century','unknown'].includes(value.record.date.precision)))issues.push('Dates require a numeric from year, BCE/CE era and supported precision.');if(!value.citations.length)issues.push('At least one HTTP(S) citation is required before submission.');issues.push(...translationProposalIssues(value));return issues}
app.post('/api/contributions',requireUser,requireApproved,async(req,res)=>{const value=normalizeContribution(req.body||{});if(!value.recordType||!value.title||!value.rationale||!value.record||typeof value.record!=='object')return res.status(400).json({error:'Record type, title, rationale and a valid proposed record are required.'});const id=randomUUID();await pool.query(`INSERT INTO contributions (id,contributor_id,action,record_type,target_record_id,title,rationale,proposed_record_json,citations_json) VALUES (?,?,?,?,?,?,?,?,?)`,[id,req.user.id,value.action,value.recordType,value.targetRecordId,value.title,value.rationale,JSON.stringify(value.record),JSON.stringify(value.citations)]);await audit(pool,req.user.id,'contribution.created','contribution',id,{recordType:value.recordType,targetRecordId:value.targetRecordId});res.status(201).json({ok:true,id,status:'draft'})})
app.get('/api/contributions/mine',requireUser,async(req,res)=>{const rows=await pool.query(`SELECT c.*,COALESCE((SELECT JSON_ARRAYAGG(JSON_OBJECT('decision',r.decision,'publicComment',r.public_comment,'createdAt',r.created_at)) FROM contribution_reviews r WHERE r.contribution_id=c.id),JSON_ARRAY()) reviews FROM contributions c WHERE contributor_id=? ORDER BY updated_at DESC`,[req.user.id]);res.json({contributions:rows.map(row=>({...row,proposed_record_json:safeJson(row.proposed_record_json),citations_json:safeJson(row.citations_json),reviews:safeJson(row.reviews)||[]}))})})
app.put('/api/contributions/:id',requireUser,requireApproved,async(req,res)=>{const current=(await pool.query('SELECT * FROM contributions WHERE id=? AND contributor_id=? LIMIT 1',[req.params.id,req.user.id]))[0];if(!current)return res.status(404).json({error:'Contribution not found.'});if(!['draft','changes-requested'].includes(current.status))return res.status(409).json({error:'Only drafts or change requests can be edited.'});const value=normalizeContribution(req.body||{});if(!value.recordType||!value.title||!value.rationale||!value.record)return res.status(400).json({error:'Complete contribution fields are required.'});await pool.query(`UPDATE contributions SET action=?,record_type=?,target_record_id=?,title=?,rationale=?,proposed_record_json=?,citations_json=?,version=version+1,status='draft' WHERE id=?`,[value.action,value.recordType,value.targetRecordId,value.title,value.rationale,JSON.stringify(value.record),JSON.stringify(value.citations),current.id]);res.json({ok:true,status:'draft'})})
app.post('/api/contributions/:id/submit',requireUser,requireApproved,async(req,res)=>{const current=(await pool.query(`SELECT * FROM contributions WHERE id=? AND contributor_id=? AND status='draft' LIMIT 1`,[req.params.id,req.user.id]))[0];if(!current)return res.status(409).json({error:'Only a draft can be submitted.'});const issues=proposalIssues({action:current.action,recordType:current.record_type,targetRecordId:current.target_record_id,title:current.title,rationale:current.rationale,record:safeJson(current.proposed_record_json),citations:safeJson(current.citations_json)||[]});if(issues.length)return res.status(422).json({error:issues.join(' '),issues});await pool.query(`UPDATE contributions SET status='submitted',submitted_at=UTC_TIMESTAMP(3) WHERE id=?`,[current.id]);await audit(pool,req.user.id,'contribution.submitted','contribution',req.params.id);res.json({ok:true,status:'submitted'})})

app.post('/api/collaboration-proposals',requireUser,requireApproved,async(req,res)=>{const entityKind=['organization','university','individual'].includes(req.body?.entityKind)?req.body.entityKind:null;const organizationName=clean(req.body?.organizationName,255),contactName=clean(req.body?.contactName,160),contactEmail=clean(req.body?.contactEmail,254),websiteUrl=clean(req.body?.websiteUrl,1000)||null,collaborationType=clean(req.body?.collaborationType,120),scopeEn=clean(req.body?.scopeEn,10000),scopeKn=clean(req.body?.scopeKn,10000);if(!entityKind||!organizationName||!contactName||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contactEmail)||!collaborationType||!scopeEn||!scopeKn)return res.status(400).json({error:'Entity, contact, collaboration type and bilingual scope are required.'});if(websiteUrl&&!/^https:\/\//i.test(websiteUrl))return res.status(400).json({error:'Collaboration website must use HTTPS.'});const id=randomUUID();await pool.query(`INSERT INTO collaboration_proposals (id,proposer_user_id,entity_kind,organization_name,contact_name,contact_email,website_url,collaboration_type,scope_en,scope_kn) VALUES (?,?,?,?,?,?,?,?,?,?)`,[id,req.user.id,entityKind,organizationName,contactName,contactEmail,websiteUrl,collaborationType,scopeEn,scopeKn]);await audit(pool,req.user.id,'collaboration.submitted','collaboration-proposal',id,{entityKind,organizationName,collaborationType});res.status(201).json({ok:true,id,status:'submitted'})})
app.get('/api/collaboration-proposals/mine',requireUser,requireApproved,async(req,res)=>{const rows=await pool.query('SELECT id,entity_kind,organization_name,collaboration_type,scope_en,scope_kn,status,reviewer_note,reviewed_at,created_at FROM collaboration_proposals WHERE proposer_user_id=? ORDER BY created_at DESC',[req.user.id]);res.json({proposals:rows})})
app.get('/api/administration/collaboration-proposals',requireUser,requireApproved,requireRole('reviewer','administrator'),async(req,res)=>{const rows=await pool.query(`SELECT p.*,u.display_name proposer_name,u.institution_name proposer_institution FROM collaboration_proposals p JOIN users u ON u.id=p.proposer_user_id WHERE p.status IN ('submitted','under-review','changes-requested') ORDER BY p.created_at ASC LIMIT 100`);res.json({proposals:rows})})
app.post('/api/administration/collaboration-proposals/:id/decision',requireUser,requireApproved,requireRole('reviewer','administrator'),async(req,res)=>{const decision=req.body?.decision,status=decision==='approve'?'approved':decision==='request-changes'?'changes-requested':decision==='decline'?'declined':null,note=clean(req.body?.note,10000);if(!status||!note)return res.status(400).json({error:'A decision and reviewer note are required.'});const result=await pool.query(`UPDATE collaboration_proposals SET status=?,reviewer_user_id=?,reviewer_note=?,reviewed_at=UTC_TIMESTAMP(3) WHERE id=? AND status IN ('submitted','under-review','changes-requested')`,[status,req.user.id,note,req.params.id]);if(!result.affectedRows)return res.status(409).json({error:'Proposal is no longer awaiting review.'});await audit(pool,req.user.id,`collaboration.${status}`,'collaboration-proposal',req.params.id,{decision});res.json({ok:true,status})})

app.get('/api/reviews/queue',requireUser,requireApproved,requireRole('reviewer','administrator'),async(req,res)=>{const rows=await pool.query(`SELECT c.*,u.display_name contributor_name,u.verified_badge FROM contributions c JOIN users u ON u.id=c.contributor_id WHERE c.status='submitted' AND c.contributor_id<>? ORDER BY c.submitted_at ASC LIMIT 100`,[req.user.id]);res.json({contributions:rows.map(row=>({...row,proposed_record_json:safeJson(row.proposed_record_json),citations_json:safeJson(row.citations_json)}))})})
app.post('/api/reviews/:contributionId',requireUser,requireApproved,requireRole('reviewer','administrator'),async(req,res)=>{
  const decision=req.body?.decision;const publicComment=clean(req.body?.publicComment,10000);if(!['approve','request-changes','reject'].includes(decision)||!publicComment)return res.status(400).json({error:'A decision and public review comment are required.'})
  const outcome=await transaction(async db=>{const rows=await db.query('SELECT * FROM contributions WHERE id=? FOR UPDATE',[req.params.contributionId]);const contribution=rows[0];if(!contribution||contribution.status!=='submitted')throw Object.assign(new Error('Contribution is no longer awaiting review.'),{status:409});if(contribution.contributor_id===req.user.id)throw Object.assign(new Error('Reviewers cannot decide their own contributions.'),{status:403});const normalizedContribution={...contribution,record:safeJson(contribution.proposed_record_json)};const assessment=normalizeTranslationAssessment(req.body?.assessment);const approvalIssues=translationApprovalIssues({decision,contribution:normalizedContribution,assessment});if(approvalIssues.length)throw Object.assign(new Error(approvalIssues.join(' ')),{status:422});const reviewId=randomUUID();await db.query(`INSERT INTO contribution_reviews (id,contribution_id,reviewer_id,contribution_version,decision,language_code,review_scope,public_comment,private_note,assessment_json) VALUES (?,?,?,?,?,?,?,?,?,?)`,[reviewId,contribution.id,req.user.id,contribution.version,decision,assessment.languageCode||null,assessment.reviewScope||null,publicComment,clean(req.body?.privateNote,10000)||null,contribution.action==='translation'?JSON.stringify(assessment):null]);const status=decision==='approve'?'approved':decision==='request-changes'?'changes-requested':'rejected';await db.query('UPDATE contributions SET status=?,decided_at=UTC_TIMESTAMP(3) WHERE id=?',[status,contribution.id]);if(decision==='approve'){const citations=safeJson(contribution.citations_json)||[];const contributorPoints=20+Math.min(citations.length,5)*2;await db.query(`INSERT INTO karma_ledger (id,user_id,contribution_id,points,reason,note,created_by) VALUES (?,?,?,?,?,?,?)`,[randomUUID(),contribution.contributor_id,contribution.id,contributorPoints,'approved-contribution',`Approved contribution with ${citations.length} citation(s).`,req.user.id]);await db.query(`INSERT INTO karma_ledger (id,user_id,review_id,points,reason,note,created_by) VALUES (?,?,?,?,?,?,?)`,[randomUUID(),req.user.id,reviewId,5,'approved-review','Completed an approval review.',req.user.id])}await audit(db,req.user.id,`contribution.${status}`,'contribution',contribution.id,{reviewId,decision,reviewScope:assessment.reviewScope||null,languageCode:assessment.languageCode||null});return {status,reviewId}});res.json({ok:true,...outcome})
})

app.get('/api/community/leaderboard',async(req,res)=>{const rows=await pool.query(`SELECT u.id,u.display_name,u.display_name_kn,u.profession,u.institution_name,u.verified_badge,COALESCE(SUM(k.points),0) karma FROM users u LEFT JOIN karma_ledger k ON k.user_id=u.id WHERE u.account_status='approved' GROUP BY u.id ORDER BY karma DESC,u.display_name ASC LIMIT 100`);res.json({people:rows.map(row=>({...row,verified_badge:Boolean(row.verified_badge),karma:Number(row.karma)}))})})

app.get('/api/administration/users',requireUser,requireRole('administrator'),async(req,res)=>{const rows=await pool.query(`SELECT u.id,u.email,u.display_name,u.display_name_kn,u.profession,u.affiliation_type,u.institution_name,u.account_status,u.verified_badge,u.created_at,COALESCE(GROUP_CONCAT(r.role),'') roles FROM users u LEFT JOIN user_roles r ON r.user_id=u.id GROUP BY u.id ORDER BY FIELD(u.account_status,'pending','approved','suspended','rejected'),u.created_at`);res.json({users:rows})})
app.patch('/api/administration/users/:id',requireUser,requireRole('administrator'),async(req,res)=>{const status=req.body?.accountStatus;if(!['approved','rejected','suspended'].includes(status))return res.status(400).json({error:'Account decision is invalid.'});await transaction(async db=>{await db.query("UPDATE users SET account_status=?,approved_by=?,approved_at=IF(?='approved',UTC_TIMESTAMP(3),approved_at),rejection_reason=? WHERE id=?",[status,req.user.id,status,clean(req.body?.reason,500)||null,req.params.id]);for(const role of (Array.isArray(req.body?.roles)?req.body.roles:[]).filter(role=>['reviewer','verification-officer','exporter','administrator'].includes(role)))await db.query('INSERT IGNORE INTO user_roles (user_id,role,appointed_by) VALUES (?,?,?)',[req.params.id,role,req.user.id]);await audit(db,req.user.id,`account.${status}`,'user',req.params.id,{roles:req.body?.roles||[]})});res.json({ok:true,status})})
app.get('/api/administration/verifications',requireUser,requireRole('verification-officer','administrator'),async(req,res)=>{const rows=await pool.query(`SELECT v.id,v.user_id,v.institution_name,v.institutional_identifier,v.document_mime,v.document_size,v.status,v.created_at,u.display_name,u.email FROM verification_requests v JOIN users u ON u.id=v.user_id WHERE v.status='pending' ORDER BY v.created_at`);res.json({requests:rows})})
app.get('/api/administration/verifications/:id/document',requireUser,requireRole('verification-officer','administrator'),async(req,res)=>{const row=(await pool.query('SELECT * FROM verification_requests WHERE id=? LIMIT 1',[req.params.id]))[0];if(!row)return res.status(404).json({error:'Verification request not found.'});if(!row.document_storage_key)return res.status(410).json({error:'This private document has been deleted under the retention policy.'});const encrypted=await readFile(path.join(config.uploadDir,row.document_storage_key));res.type(row.document_mime).set('Cache-Control','no-store').send(decryptDocument(encrypted,config.documentEncryptionKey))})
app.post('/api/administration/verifications/:id/decision',requireUser,requireRole('verification-officer','administrator'),async(req,res)=>{const status=req.body?.decision==='approve'?'approved':req.body?.decision==='reject'?'rejected':null;if(!status)return res.status(400).json({error:'Verification decision is invalid.'});await transaction(async db=>{const row=(await db.query('SELECT * FROM verification_requests WHERE id=? FOR UPDATE',[req.params.id]))[0];if(!row||row.status!=='pending')throw Object.assign(new Error('Request is no longer pending.'),{status:409});await db.query('UPDATE verification_requests SET status=?,review_note=?,reviewed_by=?,reviewed_at=UTC_TIMESTAMP(3),delete_after=DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 30 DAY) WHERE id=?',[status,clean(req.body?.note,1000)||null,req.user.id,row.id]);if(status==='approved')await db.query('UPDATE users SET verified_badge=1 WHERE id=?',[row.user_id]);await audit(db,req.user.id,`verification.${status}`,'verification-request',row.id,{userId:row.user_id})});res.json({ok:true,status})})

app.post('/api/administration/certificates',requireUser,requireRole('administrator'),async(req,res)=>{const userId=clean(req.body?.userId,36);const from=clean(req.body?.periodFrom,10);const to=clean(req.body?.periodTo,10);if(!userId||!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to))return res.status(400).json({error:'User and certificate period are required.'});const totals=await pool.query(`SELECT COALESCE(SUM(CASE WHEN reason IN ('approved-contribution','citation-quality') THEN points ELSE 0 END),0) contribution_points,COALESCE(SUM(CASE WHEN reason IN ('approved-review','verification-service') THEN points ELSE 0 END),0) reviewer_points FROM karma_ledger WHERE user_id=? AND DATE(created_at) BETWEEN ? AND ?`,[userId,from,to]);const id=randomUUID(),code=randomToken(18).slice(0,32);await pool.query(`INSERT INTO certificates (id,verification_code,user_id,title_en,title_kn,period_from,period_to,contribution_points,reviewer_points,statement_en,statement_kn,issued_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[id,code,userId,clean(req.body?.titleEn,255)||'Certificate of contribution',clean(req.body?.titleKn,255)||'ಕೊಡುಗೆ ಪ್ರಮಾಣಪತ್ರ',from,to,totals[0].contribution_points,totals[0].reviewer_points,clean(req.body?.statementEn,3000)||'For contributions to Kannada language technology and the Karnataka Historical Atlas.',clean(req.body?.statementKn,3000)||'ಕನ್ನಡ ಭಾಷಾ ತಂತ್ರಜ್ಞಾನ ಮತ್ತು ಕರ್ನಾಟಕ ಇತಿಹಾಸ ಭೂಪಟಕ್ಕೆ ನೀಡಿದ ಕೊಡುಗೆಗಾಗಿ.',req.user.id]);await audit(pool,req.user.id,'certificate.issued','certificate',id,{userId,code});res.status(201).json({ok:true,id,verificationCode:code})})
app.get('/api/certificates/mine',requireUser,async(req,res)=>{const rows=await pool.query('SELECT * FROM certificates WHERE user_id=? ORDER BY issued_at DESC',[req.user.id]);res.json({certificates:rows})})
app.get('/api/certificates/verify/:code',async(req,res)=>{const rows=await pool.query(`SELECT c.verification_code,c.title_en,c.title_kn,c.period_from,c.period_to,c.contribution_points,c.reviewer_points,c.statement_en,c.statement_kn,c.issued_at,c.revoked_at,u.display_name,u.display_name_kn FROM certificates c JOIN users u ON u.id=c.user_id WHERE c.verification_code=? LIMIT 1`,[req.params.code]);if(!rows.length)return res.status(404).json({error:'Certificate not found.'});res.json({certificate:rows[0],valid:!rows[0].revoked_at})})

app.use('/api',(req,res)=>res.status(404).json({error:'API route not found.'}))
if(existsSync(config.publicDir)){app.use(express.static(config.publicDir,{index:false,maxAge:config.env==='production'?'1h':0}));app.use((req,res,next)=>{if(req.method!=='GET')return next();res.sendFile(path.join(config.publicDir,'index.html'))})}
app.use((error,req,res,next)=>{console.error(error);if(res.headersSent)return next(error);res.status(error.status||500).json({error:error.status?error.message:'The service could not complete this request.'})})

const server=app.listen(config.port,()=>console.log(`Karnataka Historical Atlas community service listening on ${config.port}`))
const shutdown=async()=>{server.close();await closeDatabase()}
process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown)

export { app }
