import { useCallback, useEffect, useState } from 'react'

const words={
  kn:{title:'ಸಮುದಾಯ ಕೊಡುಗೆ',intro:'ವಿದ್ಯಾರ್ಥಿಗಳು, ಸಂಶೋಧಕರು, ಶಿಕ್ಷಕರು ಮತ್ತು ಇತಿಹಾಸಾಸಕ್ತರು ಆಧಾರಸಹಿತ ಜ್ಞಾನವನ್ನು ಸೂಚಿಸಬಹುದು. ಪ್ರತಿಯೊಂದು ಬದಲಾವಣೆಯೂ ಪರಿಶೀಲನೆಯ ನಂತರವೇ ಪ್ರಕಟವಾಗುತ್ತದೆ.',signIn:'ಲಾಗಿನ್',register:'ನೋಂದಣಿ',name:'ಹೆಸರು',nameKn:'ಕನ್ನಡದಲ್ಲಿ ಹೆಸರು',email:'ಇಮೇಲ್',password:'ಗುಪ್ತಪದ (ಕನಿಷ್ಠ 12 ಅಕ್ಷರಗಳು)',profession:'ಪ್ರಸ್ತುತ ವೃತ್ತಿ',affiliation:'ಸಂಸ್ಥೆಯ ಸಂಬಂಧ',institution:'ಸಂಸ್ಥೆಯ ಹೆಸರು',create:'ಖಾತೆ ಅನುಮೋದನೆಗೆ ಕಳುಹಿಸಿ',pending:'ನಿಮ್ಮ ಖಾತೆ ಸಂಚಯದ ಅನುಮೋದನೆಗಾಗಿ ಕಾಯುತ್ತಿದೆ.',logout:'ಲಾಗ್ ಔಟ್',dashboard:'ನನ್ನ ಕೊಡುಗೆಗಳು',newContribution:'ಹೊಸ ಬದಲಾವಣೆ ಸೂಚಿಸಿ',recordType:'ದಾಖಲೆಯ ವಿಧ',action:'ಬದಲಾವಣೆಯ ವಿಧ',target:'ಈಗಿರುವ ದಾಖಲೆಯ ಸ್ಥಿರ ID (ಇದ್ದರೆ)',proposalTitle:'ಸೂಚನೆಯ ಶೀರ್ಷಿಕೆ',rationale:'ಕಾರಣ ಮತ್ತು ಐತಿಹಾಸಿಕ ವಿವರಣೆ',record:'ಸೂಚಿತ ದಾಖಲೆ (JSON)',citations:'ಆಧಾರಗಳು — ಪ್ರತಿ ಸಾಲು: URL | ಶೀರ್ಷಿಕೆ | ಪುಟ/ಸ್ಥಳ',save:'ಕರಡು ಉಳಿಸಿ',submit:'ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಿ',verification:'ಸಂಸ್ಥೆ ಪರಿಶೀಲನೆ',verificationHelp:'ಪರಿಶೀಲಿತ ಗುರುತಿಗಾಗಿ ಸಂಸ್ಥೆಯ ID ಕಾರ್ಡ್‌ನ JPEG, PNG ಅಥವಾ PDF (ಗರಿಷ್ಠ 5 MB) ಕಳುಹಿಸಿ. ಅದು ಖಾಸಗಿಯಾಗಿ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಆಗಿ ಉಳಿಯುತ್ತದೆ.',idNumber:'ಸಂಸ್ಥೆಯ ಗುರುತು ಸಂಖ್ಯೆ (ಐಚ್ಛಿಕ)',upload:'ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಿ',karma:'ಕರ್ಮ ಅಂಕಗಳು',leaderboard:'ಸಮುದಾಯ ಗೌರವಪಟ್ಟಿ',reviews:'ಪರಿಶೀಲನಾ ಸರದಿ',approve:'ಅನುಮೋದಿಸಿ',changes:'ತಿದ್ದುಪಡಿ ಕೇಳಿ',reject:'ತಿರಸ್ಕರಿಸಿ',comment:'ಕೊಡುಗೆದಾರರಿಗೆ ಸಾರ್ವಜನಿಕ ಟಿಪ್ಪಣಿ',accounts:'ಖಾತೆ ಅನುಮೋದನೆ',approveAccount:'ಖಾತೆ ಅನುಮೋದಿಸಿ',makeReviewer:'ಪರಿಶೀಲಕರನ್ನಾಗಿ ನೇಮಿಸಿ',certificates:'ನನ್ನ ಪ್ರಮಾಣಪತ್ರಗಳು',liveUnavailable:'ಲೈವ್ ಕೊಡುಗೆ ಸೇವೆ ಈಗ ಸಂಪರ್ಕದಲ್ಲಿಲ್ಲ. ಈ ಸ್ಥಿರ ಆವೃತ್ತಿಯಲ್ಲಿ ಪ್ರಕಟಿತ ಅಟ್ಲಸ್‌ನ್ನು ವೀಕ್ಷಿಸಬಹುದು.',privacy:'ID ಕಾರ್ಡ್ ಸಾರ್ವಜನಿಕವಾಗುವುದಿಲ್ಲ; ನಿರ್ಣಯದ 30 ದಿನಗಳ ನಂತರ ಅಳಿಸುವುದಕ್ಕೆ ಗುರುತಿಸಲಾಗುತ್ತದೆ.',status:'ಸ್ಥಿತಿ',verified:'ಪರಿಶೀಲಿತ',roles:'ಪಾತ್ರಗಳು',translationProtocol:'ಕನ್ನಡ ಅನುವಾದ ಪರಿಶೀಲನೆ',sourceEnglish:'ಮೂಲ / ಪ್ರಕಟಿತ ಇಂಗ್ಲಿಷ್',kannadaDraft:'ಕನ್ನಡ ಕರಡು',sourceMatch:'ಮೂಲ ಪಾಠ ಮತ್ತು ಆವೃತ್ತಿಗೆ ಹೊಂದಿದೆ',semanticFidelity:'ಅರ್ಥ ಮತ್ತು ವಾಕ್ಯಸಂಬಂಧ ನಿಖರವಾಗಿದೆ',namesAndDates:'ವ್ಯಕ್ತಿನಾಮ, ಸ್ಥಳನಾಮ ಮತ್ತು ದಿನಾಂಕ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',historicalTerminology:'ಐತಿಹಾಸಿಕ ಪದಪ್ರಯೋಗ ಸೂಕ್ತವಾಗಿದೆ',lineCompleteness:'ಎಲ್ಲ ಸಾಲುಗಳು ಒಂದಕ್ಕೊಂದು ಹೊಂದಿವೆ',attestation:'ಈ ಕನ್ನಡ ಅನುವಾದವನ್ನು ನಾನು ಸಂಪೂರ್ಣವಾಗಿ ಪರಿಶೀಲಿಸಿದ್ದೇನೆ.'},
  en:{title:'Community contributions',intro:'Students, researchers, teachers and history enthusiasts can suggest cited knowledge. Every change is reviewed before publication.',signIn:'Sign in',register:'Register',name:'Name',nameKn:'Name in Kannada',email:'Email',password:'Password (at least 12 characters)',profession:'Current profession',affiliation:'Institution affiliation',institution:'Institution name',create:'Request account approval',pending:'Your account is awaiting Sanchaya approval.',logout:'Log out',dashboard:'My contributions',newContribution:'Suggest a change',recordType:'Record type',action:'Change type',target:'Existing stable record ID (if any)',proposalTitle:'Proposal title',rationale:'Rationale and historical explanation',record:'Proposed record (JSON)',citations:'Sources — one per line: URL | title | page/locator',save:'Save draft',submit:'Submit for review',verification:'Institution verification',verificationHelp:'Upload a JPEG, PNG or PDF institution ID (maximum 5 MB) for a verified badge. It is encrypted in private storage.',idNumber:'Institution identifier (optional)',upload:'Request verification',karma:'Karma points',leaderboard:'Community honour roll',reviews:'Review queue',approve:'Approve',changes:'Request changes',reject:'Reject',comment:'Public comment for contributor',accounts:'Account approvals',approveAccount:'Approve account',makeReviewer:'Appoint reviewer',certificates:'My certificates',liveUnavailable:'The live contribution service is not connected. You can continue viewing the published atlas in this static edition.',privacy:'ID cards are never public and are marked for deletion 30 days after a decision.',status:'Status',verified:'Verified',roles:'Roles',translationProtocol:'Kannada translation review',sourceEnglish:'Source / published English',kannadaDraft:'Kannada draft',sourceMatch:'Matches the cited text and edition',semanticFidelity:'Meaning and syntax are faithfully represented',namesAndDates:'Names, places and dates are checked',historicalTerminology:'Historical terminology is appropriate',lineCompleteness:'Every source line has a matching translation',attestation:'I have reviewed this Kannada translation in full.'}
}
const collaborationWords={
  kn:{title:'ಸಹಯೋಗ ಪ್ರಸ್ತಾಪ',mine:'ನನ್ನ ಸಹಯೋಗ ಪ್ರಸ್ತಾಪಗಳು',queue:'ಸಹಯೋಗ ಪರಿಶೀಲನಾ ಸರದಿ',entity:'ಸಹಯೋಗಿಯ ವಿಧ',organization:'ಸಂಸ್ಥೆ / ವ್ಯಕ್ತಿಯ ಹೆಸರು',contact:'ಸಂಪರ್ಕ ವ್ಯಕ್ತಿ',contactEmail:'ಸಂಪರ್ಕ ಇಮೇಲ್',website:'ವೆಬ್‌ಸೈಟ್ (ಐಚ್ಛಿಕ)',type:'ಸಹಯೋಗದ ವಿಧ',scopeKn:'ಕನ್ನಡದಲ್ಲಿ ವ್ಯಾಪ್ತಿ',scopeEn:'ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ವ್ಯಾಪ್ತಿ',send:'ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಿ',note:'ಪರಿಶೀಲಕರ ಟಿಪ್ಪಣಿ',approve:'ಅನುಮೋದಿಸಿ',changes:'ತಿದ್ದುಪಡಿ ಕೇಳಿ',decline:'ನಿರಾಕರಿಸಿ'},
  en:{title:'Propose a collaboration',mine:'My collaboration proposals',queue:'Collaboration review queue',entity:'Collaborator type',organization:'Organization / individual name',contact:'Contact person',contactEmail:'Contact email',website:'Website (optional)',type:'Collaboration type',scopeKn:'Scope in Kannada',scopeEn:'Scope in English',send:'Submit for review',note:'Reviewer note',approve:'Approve',changes:'Request changes',decline:'Decline'}
}
const professions=['student','researcher','teacher','faculty','lecturer','historian','public','other']
const affiliations=['none','school','college','university','research-institute','museum','government','nonprofit','other']
const recordTypes=['event','polity','person','reign','place','work','inscription','culturalHeritage','territorialExtent','heritageCandidate','source']
const api=async(path,options={})=>{const response=await fetch(`${import.meta.env.VITE_COMMUNITY_API_URL||''}/api${path}`,{credentials:'include',...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data}
const parseCitations=value=>value.split('\n').map(line=>line.split('|').map(part=>part.trim())).filter(parts=>/^https?:\/\//i.test(parts[0])).map(([url,title='',locator=''])=>({url,title,locator}))

export default function Community({locale}){
  const t=words[locale],c=collaborationWords[locale],[service,setService]=useState('loading'),[me,setMe]=useState(null),[mode,setMode]=useState('login'),[notice,setNotice]=useState(''),[error,setError]=useState(''),[mine,setMine]=useState([]),[leaders,setLeaders]=useState([]),[queue,setQueue]=useState([]),[users,setUsers]=useState([]),[verifications,setVerifications]=useState([]),[certificates,setCertificates]=useState([]),[collaborationMine,setCollaborationMine]=useState([]),[collaborationQueue,setCollaborationQueue]=useState([])
  const refresh=useCallback(async()=>{setError('');try{await api('/health');setService('online');const [leaderResult,meResult]=await Promise.all([api('/community/leaderboard'),api('/auth/me').catch(()=>null)]);setLeaders(leaderResult.people||[]);setMe(meResult?.user||null)}catch{setService('offline');setMe(null)}},[])
  useEffect(()=>{refresh()},[refresh])
  const loadPrivate=useCallback(async user=>{if(!user)return;const tasks=[api('/contributions/mine').then(v=>setMine(v.contributions||[])),api('/certificates/mine').then(v=>setCertificates(v.certificates||[]))];if(user.accountStatus==='approved')tasks.push(api('/collaboration-proposals/mine').then(v=>setCollaborationMine(v.proposals||[])));if(user.roles?.some(role=>['reviewer','administrator'].includes(role))){tasks.push(api('/reviews/queue').then(v=>setQueue(v.contributions||[])));tasks.push(api('/administration/collaboration-proposals').then(v=>setCollaborationQueue(v.proposals||[])))}if(user.roles?.includes('administrator'))tasks.push(api('/administration/users').then(v=>setUsers(v.users||[])));if(user.roles?.some(role=>['verification-officer','administrator'].includes(role)))tasks.push(api('/administration/verifications').then(v=>setVerifications(v.requests||[])));await Promise.all(tasks)},[])
  useEffect(()=>{loadPrivate(me).catch(err=>setError(err.message))},[me,loadPrivate])
  const action=async work=>{setError('');setNotice('');try{const message=await work();setNotice(message||'✓');await refresh();await loadPrivate(me)}catch(err){setError(err.message)}}
  if(service==='loading')return <section className="community-page"><p>…</p></section>
  return <section className="community-page" id="community"><div className="community-hero"><p className="eyebrow">Sanchaya · Community review</p><h2>{t.title}</h2><p>{t.intro}</p></div>{error&&<p className="community-alert error">{error}</p>}{notice&&<p className="community-alert success">{notice}</p>}
    {service==='offline'?<div className="community-offline"><h3>{t.liveUnavailable}</h3>{import.meta.env.VITE_LIVE_PORTAL_URL&&<a href={import.meta.env.VITE_LIVE_PORTAL_URL}>{import.meta.env.VITE_LIVE_PORTAL_URL}</a>}</div>:!me?<Auth locale={locale} t={t} mode={mode} setMode={setMode} run={action} onLogin={setMe}/>:<>
      <div className="community-user"><div><strong>{me.displayNameKn||me.displayName} {me.verifiedBadge&&<span title={t.verified}>✓</span>}</strong><small>{me.institutionName||me.profession} · {t.roles}: {me.roles.join(', ')}</small></div><b>{me.karma} {t.karma}</b><button onClick={()=>action(async()=>{await api('/auth/logout',{method:'POST'});setMe(null);return ''})}>{t.logout}</button></div>
      {me.accountStatus!=='approved'?<><p className="community-alert pending">{t.pending}</p><VerificationForm t={t} run={action}/></>:<><div className="community-columns"><div><ContributionForm t={t} run={action}/><VerificationForm t={t} run={action}/></div><MyContributions t={t} items={mine} run={action}/></div><CollaborationProposalForm c={c} run={action}/><CollaborationList c={c} items={collaborationMine}/></>}
      {me.roles.some(role=>['reviewer','administrator'].includes(role))&&<ReviewQueue t={t} items={queue} run={action}/>} 
      {me.roles.some(role=>['reviewer','administrator'].includes(role))&&<CollaborationReviewQueue c={c} items={collaborationQueue} run={action}/>} 
      {me.roles.includes('administrator')&&<AccountQueue t={t} items={users} run={action}/>} 
      {me.roles.some(role=>['verification-officer','administrator'].includes(role))&&<VerificationQueue t={t} items={verifications} run={action}/>} 
      <CertificateList t={t} items={certificates} locale={locale}/>
    </>}
    <Leaderboard t={t} people={leaders}/><div className="community-principles"><strong>{t.verification}</strong><p>{t.privacy}</p><p>20 points + 2 per cited source (up to five) for an approved contribution · 5 points for its reviewer.</p></div>
  </section>
}

function Auth({locale,t,mode,setMode,run,onLogin}){const submit=event=>{event.preventDefault();const form=new FormData(event.currentTarget);run(async()=>{if(mode==='login'){const result=await api('/auth/login',{method:'POST',body:JSON.stringify({email:form.get('email'),password:form.get('password')})});onLogin(result.user);return '✓'}await api('/auth/register',{method:'POST',body:JSON.stringify({displayName:form.get('name'),displayNameKn:form.get('nameKn'),email:form.get('email'),password:form.get('password'),profession:form.get('profession'),affiliationType:form.get('affiliation'),institutionName:form.get('institution'),preferredLocale:locale,acceptTerms:true,acceptPrivacy:true})});setMode('login');return t.pending})};return <div className="community-auth"><div className="community-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>{t.signIn}</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>{t.register}</button></div><form onSubmit={submit}>{mode==='register'&&<><label>{t.name}<input name="name" required/></label><label>{t.nameKn}<input name="nameKn" lang="kn"/></label><label>{t.profession}<select name="profession">{professions.map(value=><option key={value}>{value}</option>)}</select></label><label>{t.affiliation}<select name="affiliation">{affiliations.map(value=><option key={value}>{value}</option>)}</select></label><label>{t.institution}<input name="institution"/></label></>}<label>{t.email}<input name="email" type="email" required/></label><label>{t.password}<input name="password" type="password" minLength="12" required/></label><button className="community-primary">{mode==='login'?t.signIn:t.create}</button></form></div>}
function ContributionForm({t,run}){const submit=event=>{event.preventDefault();const form=new FormData(event.currentTarget);run(async()=>{let record;try{record=JSON.parse(form.get('record'))}catch{throw new Error('Proposed record must be valid JSON.')}await api('/contributions',{method:'POST',body:JSON.stringify({recordType:form.get('recordType'),action:form.get('action'),targetRecordId:form.get('target'),title:form.get('title'),rationale:form.get('rationale'),proposedRecord:JSON.stringify(record),citations:parseCitations(form.get('citations'))})});event.currentTarget.reset();return 'Draft saved.'})};return <form className="community-card community-form" onSubmit={submit}><h3>{t.newContribution}</h3><div className="community-form-grid"><label>{t.recordType}<select name="recordType">{recordTypes.map(value=><option key={value}>{value}</option>)}</select></label><label>{t.action}<select name="action">{['create','update','correction','citation','translation'].map(value=><option key={value}>{value}</option>)}</select></label></div><label>{t.target}<input name="target" placeholder="event-talikota-1565"/></label><label>{t.proposalTitle}<input name="title" required/></label><label>{t.rationale}<textarea name="rationale" required rows="4"/></label><label>{t.record}<textarea name="record" required rows="8" defaultValue={'{\n  "id": "",\n  "name": { "kn": "", "en": "" }\n}'}/></label><label>{t.citations}<textarea name="citations" required rows="4" placeholder="https://… | Epigraphia Carnatica | Vol. 10, p. 42"/></label><button className="community-primary">{t.save}</button></form>}
function VerificationForm({t,run}){const submit=event=>{event.preventDefault();const form=new FormData(event.currentTarget);run(async()=>{await api('/verification-requests',{method:'POST',body:form});event.currentTarget.reset();return 'Verification requested.'})};return <form className="community-card community-form" onSubmit={submit}><h3>{t.verification}</h3><p>{t.verificationHelp}</p><label>{t.institution}<input name="institutionName" required/></label><label>{t.idNumber}<input name="institutionalIdentifier"/></label><input name="institutionId" type="file" accept="image/jpeg,image/png,application/pdf" required/><small>{t.privacy}</small><button className="community-primary">{t.upload}</button></form>}
function MyContributions({t,items,run}){return <section className="community-card"><h3>{t.dashboard}</h3>{!items.length&&<p>—</p>}{items.map(item=><article className="contribution-item" key={item.id}><span className={`community-status ${item.status}`}>{item.status}</span><strong>{item.title}</strong><small>{item.record_type} · {item.action} · v{item.version}</small>{item.reviews?.map((review,index)=><p key={index}>{review.publicComment}</p>)}{item.status==='draft'&&<button onClick={()=>run(async()=>{await api(`/contributions/${item.id}/submit`,{method:'POST'});return 'Submitted for review.'})}>{t.submit}</button>}</article>)}</section>}
function CollaborationProposalForm({c,run}){const submit=event=>{event.preventDefault();const form=new FormData(event.currentTarget);run(async()=>{await api('/collaboration-proposals',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});event.currentTarget.reset();return 'Collaboration proposal submitted for review.'})};return <form className="community-card community-form community-wide" onSubmit={submit}><h3>{c.title}</h3><div className="community-form-grid"><label>{c.entity}<select name="entityKind"><option value="organization">organization</option><option value="university">university</option><option value="individual">individual</option></select></label><label>{c.type}<input name="collaborationType" required/></label><label>{c.organization}<input name="organizationName" required/></label><label>{c.contact}<input name="contactName" required/></label><label>{c.contactEmail}<input name="contactEmail" type="email" required/></label><label>{c.website}<input name="websiteUrl" type="url" placeholder="https://"/></label></div><label>{c.scopeKn}<textarea name="scopeKn" lang="kn" rows="4" required/></label><label>{c.scopeEn}<textarea name="scopeEn" rows="4" required/></label><button className="community-primary">{c.send}</button></form>}
function CollaborationList({c,items}){return <section className="community-card community-wide"><h3>{c.mine}</h3>{!items.length&&<p>—</p>}{items.map(item=><article className="contribution-item" key={item.id}><span className={`community-status ${item.status}`}>{item.status}</span><strong>{item.organization_name}</strong><small>{item.entity_kind} · {item.collaboration_type}</small>{item.reviewer_note&&<p>{item.reviewer_note}</p>}</article>)}</section>}
function CollaborationReviewQueue({c,items,run}){return <section className="community-card community-wide"><h3>{c.queue}</h3>{!items.length&&<p>—</p>}{items.map(item=><CollaborationReviewItem key={item.id} c={c} item={item} run={run}/>)}</section>}
function CollaborationReviewItem({c,item,run}){const [note,setNote]=useState('');const decide=decision=>run(async()=>{await api(`/administration/collaboration-proposals/${item.id}/decision`,{method:'POST',body:JSON.stringify({decision,note})});setNote('');return 'Collaboration decision recorded.'});return <article className="review-item"><header><strong>{item.organization_name}</strong><small>{item.entity_kind} · {item.collaboration_type} · {item.proposer_name}</small></header><p lang="kn">{item.scope_kn}</p><p>{item.scope_en}</p>{item.website_url&&<a href={item.website_url} target="_blank" rel="noreferrer">{item.website_url} ↗</a>}<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder={c.note}/><div className="review-actions"><button disabled={!note} onClick={()=>decide('approve')}>{c.approve}</button><button disabled={!note} onClick={()=>decide('request-changes')}>{c.changes}</button><button disabled={!note} onClick={()=>decide('decline')}>{c.decline}</button></div></article>}
function ReviewQueue({t,items,run}){return <section className="community-card community-wide"><h3>{t.reviews}</h3>{!items.length&&<p>—</p>}{items.map(item=><ReviewItem key={item.id} item={item} t={t} run={run}/>)}</section>}
function ReviewItem({item,t,run}){const [comment,setComment]=useState(''),[checks,setChecks]=useState({});const isTranslation=item.action==='translation',sections=item.proposed_record_json?.translation?.sections||[];const checkFields=[['sourceMatch',t.sourceMatch],['semanticFidelity',t.semanticFidelity],['namesAndDates',t.namesAndDates],['historicalTerminology',t.historicalTerminology],['lineCompleteness',t.lineCompleteness],['reviewerAttestation',t.attestation]];const translationReady=!isTranslation||checkFields.every(([key])=>checks[key]);const decide=decision=>run(async()=>{const assessment=isTranslation?{languageCode:'kn',reviewScope:'kannada-translation',...checks}:undefined;await api(`/reviews/${item.id}`,{method:'POST',body:JSON.stringify({decision,publicComment:comment,assessment})});setComment('');setChecks({});return 'Review recorded.'});return <article className={`review-item ${isTranslation?'translation-review':''}`}><header><strong>{item.title}</strong><small>{item.contributor_name} · {item.record_type} · {item.action}</small></header><p>{item.rationale}</p>{isTranslation?<section className="translation-review-workspace"><h4>{t.translationProtocol}</h4>{sections.map(section=><div className="translation-review-section" key={section.label}><strong>{section.label}</strong><div className="translation-review-columns"><div><b>{t.sourceEnglish}</b>{section.en.map((line,index)=><p key={`en-${index}`}><i>{index+1}</i>{line}</p>)}</div><div lang="kn"><b>{t.kannadaDraft}</b>{section.kn.map((line,index)=><p key={`kn-${index}`}><i>{index+1}</i>{line}</p>)}</div></div></div>)}<fieldset><legend>{t.translationProtocol}</legend>{checkFields.map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean(checks[key])} onChange={event=>setChecks(current=>({...current,[key]:event.target.checked}))}/><span>{label}</span></label>)}</fieldset></section>:<pre>{JSON.stringify(item.proposed_record_json,null,2)}</pre>}<div className="review-sources">{(item.citations_json||[]).map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.title||source.url} <small>{source.locator}</small> ↗</a>)}</div><textarea value={comment} onChange={event=>setComment(event.target.value)} placeholder={t.comment}/><div className="review-actions"><button disabled={!comment||!translationReady} onClick={()=>decide('approve')}>{t.approve}</button><button disabled={!comment} onClick={()=>decide('request-changes')}>{t.changes}</button><button disabled={!comment} onClick={()=>decide('reject')}>{t.reject}</button></div></article>}
function AccountQueue({t,items,run}){const today=new Date().toISOString().slice(0,10);return <section className="community-card community-wide"><h3>{t.accounts}</h3>{items.map(user=><article className="account-item" key={user.id}><div><strong>{user.display_name} {user.verified_badge?'✓':''}</strong><small>{user.email} · {user.profession} · {user.institution_name||'—'} · {user.account_status}</small></div>{user.account_status==='pending'&&<button onClick={()=>run(async()=>{await api(`/administration/users/${user.id}`,{method:'PATCH',body:JSON.stringify({accountStatus:'approved',roles:[]})});return 'Account approved.'})}>{t.approveAccount}</button>}<button onClick={()=>run(async()=>{await api(`/administration/users/${user.id}`,{method:'PATCH',body:JSON.stringify({accountStatus:'approved',roles:['reviewer']})});return 'Reviewer appointed.'})}>{t.makeReviewer}</button>{user.account_status==='approved'&&<button onClick={()=>run(async()=>{await api('/administration/certificates',{method:'POST',body:JSON.stringify({userId:user.id,periodFrom:`${new Date().getFullYear()}-01-01`,periodTo:today})});return 'Certificate issued.'})}>Issue certificate</button>}</article>)}</section>}
function VerificationQueue({t,items,run}){const decide=(id,decision)=>run(async()=>{await api(`/administration/verifications/${id}/decision`,{method:'POST',body:JSON.stringify({decision,note:decision==='approve'?'Institution identity reviewed.':'Could not verify the submitted document.'})});return 'Verification decision recorded.'});return <section className="community-card community-wide"><h3>{t.verification}</h3>{!items.length&&<p>—</p>}{items.map(item=><article className="account-item" key={item.id}><div><strong>{item.display_name}</strong><small>{item.institution_name} · {item.document_mime} · {Math.ceil(item.document_size/1024)} KB</small></div><a className="community-button" href={`${import.meta.env.VITE_COMMUNITY_API_URL||''}/api/administration/verifications/${item.id}/document`} target="_blank" rel="noreferrer">View private ID</a><button onClick={()=>decide(item.id,'approve')}>{t.approve}</button><button onClick={()=>decide(item.id,'reject')}>{t.reject}</button></article>)}</section>}
function Leaderboard({t,people}){return <section className="community-card community-leaders"><h3>{t.leaderboard}</h3><ol>{people.slice(0,20).map(person=><li key={person.id}><span><strong>{person.display_name_kn||person.display_name} {person.verified_badge&&'✓'}</strong><small>{person.institution_name||person.profession}</small></span><b>{person.karma}</b></li>)}</ol></section>}
function CertificateList({t,items,locale}){if(!items.length)return null;return <section className="community-card community-certificates"><h3>{t.certificates}</h3>{items.map(item=><article key={item.id}><p className="eyebrow">Sanchaya · Karnataka Historical Atlas</p><h4>{locale==='kn'?item.title_kn:item.title_en}</h4><p>{locale==='kn'?item.statement_kn:item.statement_en}</p><strong>{item.contribution_points+item.reviewer_points} {t.karma}</strong><code>{item.verification_code}</code><button onClick={()=>window.print()}>Print / PDF</button></article>)}</section>}
