import { useEffect, useMemo, useState } from 'react'
import { atlasData } from './data/atlas'

const primary=(value,locale)=>value?.[locale]||value?.en||value?.kn||''
const API_BASE=import.meta.env.VITE_COMMUNITY_API_URL||''
const INITIAL_VISIBLE=10
const copy={
  kn:{eyebrow:'Atlas v0.19 · ಪ್ರಕಟಣೆ ಸಿದ್ಧತೆ',title:'ಮಾನವ ಸಾಕ್ಷ್ಯ ಕಾರ್ಯವಿಧಾನ',intro:'ಶಾಸನ ಮತ್ತು ಸಾಹಿತ್ಯ ದಾಖಲೆಗಳನ್ನು ಪ್ರಕಟಿಸುವ ಮೊದಲು ಬೇಕಾದ ಕ್ಷೇತ್ರಕಾರ್ಯ, ಪಠ್ಯ, ಆಕರ ಮತ್ತು ಸ್ವತಂತ್ರ ಕನ್ನಡ ವಿಮರ್ಶೆಯನ್ನು ಒಂದೇ ಕಾರ್ಯಪಟ್ಟಿಯಲ್ಲಿ ನಿರ್ವಹಿಸಿ.',permanent:'ಅನುಮೋದಿತ ಸಂಶೋಧನಾ ಖಾತೆಯಿಂದ ಮಾಡಿದ ನಿಯೋಜನೆಗಳು ಲೈವ್ MariaDB ಸೇವೆಯಲ್ಲಿ ಶಾಶ್ವತವಾಗಿ ಉಳಿಯುತ್ತವೆ. ಖಾತೆ ಇಲ್ಲದಿದ್ದರೆ ಈ ಪುಟ ವೀಕ್ಷಣೆ ಮಾತ್ರ.',offline:'ಲೈವ್ ಸಂಶೋಧನಾ ಸೇವೆ ಸಂಪರ್ಕದಲ್ಲಿಲ್ಲ. ಈ ಪುಟ ವೀಕ್ಷಣೆ ಮಾತ್ರ; ಬದಲಾವಣೆಗಳನ್ನು ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗುವುದಿಲ್ಲ.',loading:'ಶಾಶ್ವತ ಕಾರ್ಯಪಟ್ಟಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ…',total:'ಒಟ್ಟು ಬಾಕಿ ಕಾರ್ಯಗಳು',records:'ಪರಿಶೀಲನಾ ದಾಖಲೆಗಳು',inProgress:'ಪ್ರಗತಿಯಲ್ಲಿವೆ',review:'ವಿಮರ್ಶೆಗೆ ಕಾಯುತ್ತಿವೆ',search:'ದಾಖಲೆ, ಜಿಲ್ಲೆ, ಕರ್ತೃ ಅಥವಾ ಕಾರ್ಯ ಹುಡುಕಿ',allFields:'ಎಲ್ಲ ಸಾಕ್ಷ್ಯ ವಿಧಗಳು',allStates:'ಎಲ್ಲ ಕಾರ್ಯ ಸ್ಥಿತಿಗಳು',allDomains:'ಎಲ್ಲ ಸಂಶೋಧನಾ ವಿಭಾಗಗಳು',allPriorities:'ಎಲ್ಲ ಆದ್ಯತೆಗಳು',p1Only:'P1 · ಈಗಿನ ಸಾಕ್ಷ್ಯ ಪಾಸ್',p1Label:'P1 ಆದ್ಯತೆ',epigraphy:'ಶಾಸನ · ಸಂಶೋಧನಾ ಅಭ್ಯರ್ಥಿಗಳು',literature:'ಸಾಹಿತ್ಯ · 24 ಕೃತಿಗಳು',assignee:'ನಿಯೋಜಿತ ವ್ಯಕ್ತಿ / ಸಂಸ್ಥೆ',due:'ಗಡುವು',unassigned:'ಇನ್ನೂ ನಿಯೋಜಿಸಿಲ್ಲ',procedure:'ಕಾರ್ಯ ನಿರ್ವಹಣಾ ಕ್ರಮ',steps:['ಒಂದು ದಾಖಲೆ ಮತ್ತು ಸಾಕ್ಷ್ಯ ಕಾರ್ಯವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ; ಹೊಣೆಗಾರ ವ್ಯಕ್ತಿ ಅಥವಾ ಸಂಸ್ಥೆಯನ್ನು ನಿಯೋಜಿಸಿ.','ಕೇಳಿರುವ ಕನಿಷ್ಠ ಕ್ಷೇತ್ರಗಳೊಂದಿಗೆ ಆಕರ, ಆವೃತ್ತಿ, ಪುಟ, ನಿರ್ದೇಶಾಂಕ ಅಥವಾ ಚಿತ್ರಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ.','ದಾಖಲೆಯ ಸ್ಥಿರ IDಗೆ ಸಾಕ್ಷ್ಯ ಸಲ್ಲಿಸಿ; ಮೂಲ ಸಂಶೋಧಕ ತನ್ನದೇ ಸಲ್ಲಿಕೆಯನ್ನು ಅನುಮೋದಿಸಬಾರದು.','ನೇಮಕಗೊಂಡ ಪರಿಶೀಲಕರು ಆಕರ, ಗುರುತು, ದಿನಾಂಕ, ಪರವಾನಗಿ ಮತ್ತು ದ್ವಿಭಾಷಾ ನಿಖರತೆಯನ್ನು ದಾಖಲಿಸುತ್ತಾರೆ.','ಪ್ರತಿ ಅಗತ್ಯ ಹಂತವು ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿತವಾದಾಗ ಮಾತ್ರ ಸಾರ್ವಜನಿಕ ದಾಖಲೆಯನ್ನು ಉತ್ತೇಜಿಸಿ.'],openEpigraphy:'ಶಾಸನ ಸಂಶೋಧನೆ ತೆರೆಯಿರಿ',openLiterature:'ಸಾಹಿತ್ಯ ಸಂಶೋಧನೆ ತೆರೆಯಿರಿ',contribute:'ಸಾಕ್ಷ್ಯ ಸಲ್ಲಿಸಿ',states:{todo:'ಮಾಡಬೇಕಿದೆ','in-progress':'ಪ್ರಗತಿಯಲ್ಲಿದೆ','awaiting-review':'ವಿಮರ್ಶೆಗೆ ಕಾಯುತ್ತಿದೆ',blocked:'ತಡೆಗೊಂಡಿದೆ',complete:'ಪೂರ್ಣಗೊಂಡಿದೆ'},fields:{itemEdition:'ಪ್ರತ್ಯೇಕ ಆವೃತ್ತಿ',coordinates:'ಅಧಿಕೃತ ನಿರ್ದೇಶಾಂಕ',authorityCoordinate:'ಅಧಿಕಾರ ನಿರ್ದೇಶಾಂಕ',transcription:'ಸಾಲು-ಸಾಲಿನ ಪಾಠ',translation:'ಸ್ವತಂತ್ರ ಕನ್ನಡ ವಿಮರ್ಶೆ',presentCondition:'ದಿನಾಂಕಿತ ಸ್ಥಿತಿ',authority:'ಸಂರಕ್ಷಣಾ ಪ್ರಾಧಿಕಾರ',photographs:'ಪರವಾನಗಿ ಚಿತ್ರಗಳು',creatorIdentity:'ಕರ್ತೃ ಗುರುತು',workDate:'ಕೃತಿಯ ದಿನಾಂಕ',courtContext:'ಆಸ್ಥಾನ ಸಂದರ್ಭ',bilingualDescription:'ದ್ವಿಭಾಷಾ ವಿವರಣೆ',itemCitation:'ಕೃತಿ-ಮಟ್ಟದ ಆಕರ',editionWitness:'ಆವೃತ್ತಿ / ಹಸ್ತಪ್ರತಿ ಸಾಕ್ಷ್ಯ'},showing:'ತೋರಿಸಲಾಗುತ್ತಿದೆ',loadMore:'ಇನ್ನಷ್ಟು ತೋರಿಸಿ',allShown:'ಎಲ್ಲ ಕಾರ್ಯಗಳು ತೋರಿಸಲಾಗಿದೆ'},
  en:{eyebrow:'Atlas v0.19 · Publication readiness',title:'Human evidence workflow',intro:'Manage the fieldwork, textual evidence, sources and independent Kannada review required before inscription and literary records can be published.',permanent:'Assignments made by an approved research account are stored permanently in the live MariaDB service. Without an approved account this page is view-only.',offline:'The live research service is unavailable. This page is view-only; changes are not stored in the browser.',loading:'Loading the permanent worklist…',total:'Outstanding tasks',records:'Records under review',inProgress:'In progress',review:'Awaiting review',search:'Search record, district, creator or task',allFields:'All evidence types',allStates:'All task states',allDomains:'All research domains',allPriorities:'All priorities',p1Only:'P1 · current evidence pass',p1Label:'P1 priority',epigraphy:'Epigraphy · research candidates',literature:'Literature · 24 works',assignee:'Assigned person / institution',due:'Due date',unassigned:'Unassigned',procedure:'Operating procedure',steps:['Select a record and one evidence task; assign a responsible person or institution.','Collect the source, edition, page, coordinate or photograph with every requested minimum field.','Submit evidence against the stable record ID; researchers cannot approve their own submission.','An appointed reviewer records source, identity, date, licence and bilingual-fidelity checks.','Promote a public record only after every required gate is independently verified.'],openEpigraphy:'Open epigraphy research',openLiterature:'Open literature research',contribute:'Submit evidence',states:{todo:'To do','in-progress':'In progress','awaiting-review':'Awaiting review',blocked:'Blocked',complete:'Complete'},fields:{itemEdition:'Item edition',coordinates:'Authority coordinate',authorityCoordinate:'Authority coordinate',transcription:'Line transcription',translation:'Independent Kannada review',presentCondition:'Dated condition',authority:'Protection authority',photographs:'Licensed photographs',creatorIdentity:'Creator identity',workDate:'Work date',courtContext:'Court context',bilingualDescription:'Bilingual description',itemCitation:'Item-level citation',editionWitness:'Edition / manuscript witness'},showing:'Showing',loadMore:'Load more',allShown:'All tasks shown'}
}

const sprintCopy={
  kn:{eyebrow:'Atlas v0.23 · ಸಾಕ್ಷ್ಯ ಪ್ರಚಾರ ಹಂತ',title:'ಪ್ರಕಟಣೆಗೆ ಸಮೀಪದ ಏಳು ಶಾಸನ ದಾಖಲೆಗಳು',intro:'ಏಳು ಕಡ್ಡಾಯ ಸಾಕ್ಷ್ಯ ಹಂತಗಳಲ್ಲಿ ಯಾವುದು ಪೂರ್ಣವಾಗಿದೆ, ಯಾವುದು ಮಾನವ ಪರಿಶೀಲನೆಗೆ ಬಾಕಿಯಿದೆ ಎಂಬುದನ್ನು ಇಲ್ಲಿ ಒಂದೇ ನೋಟದಲ್ಲಿ ನೋಡಿ. “ಪೂರ್ಣ” ಕಾರ್ಯ ಸ್ಥಿತಿ ಮಾತ್ರ ದಾಖಲೆಯನ್ನು ಪ್ರಕಟಿಸುವುದಿಲ್ಲ; ಎಲ್ಲಾ ಹಂತಗಳ ಸ್ವತಂತ್ರ ಅನುಮೋದನೆ ಅಗತ್ಯ.',complete:'ಪರಿಶೀಲಿತ',blocked:'ಬಾಕಿ',openTasks:'ಬಾಕಿ ಕಾರ್ಯಗಳನ್ನು ತೆರೆಯಿರಿ',gates:'ಸಾಕ್ಷ್ಯ ಹಂತಗಳು',stage:{'translation-review':'ಸ್ವತಂತ್ರ ಕನ್ನಡ ವಿಮರ್ಶೆ','evidence-capture':'ಸಾಕ್ಷ್ಯ ಸಂಗ್ರಹ','ready-for-promotion':'ಪ್ರಕಟಣೆಗೆ ಸಿದ್ಧ'}},
  en:{eyebrow:'Atlas v0.23 · evidence promotion sprint',title:'Seven inscription records closest to publication',intro:'See which of the seven mandatory evidence gates are complete and which still require human review. Completing a board assignment does not publish a record; every gate still needs independent approval.',complete:'Verified',blocked:'Open',openTasks:'Open outstanding tasks',gates:'Evidence gates',stage:{'translation-review':'Independent Kannada review','evidence-capture':'Evidence capture','ready-for-promotion':'Ready for promotion'}},
}

const p1Priority=(recordId)=>recordId.includes('sannati')?1:recordId.includes('maski')?2:['hirehadagalli','kodaganur','punisaraja','yusuf-adil','shahapur'].some(value=>recordId.includes(value))?3:4
const candidates=atlasData.inscriptionAudits.flatMap(audit=>(audit.priorityCandidates||[]).map(candidate=>({...candidate,district:audit.district})))
const placeById=new Map(atlasData.places.map(place=>[place.id,place]))
const inscriptionById=new Map(atlasData.inscriptions.map(inscription=>[inscription.id,inscription]))
const p1PromotionCandidates=candidates.filter(candidate=>p1Priority(candidate.id)<4).sort((a,b)=>p1Priority(a.id)-p1Priority(b.id)||a.id.localeCompare(b.id))
const inscriptionTasks=candidates.flatMap(candidate=>(candidate.promotionReview?.evidenceRequests||[]).map(request=>({id:`${candidate.id}:${request.field}`,domain:'epigraphy',recordId:candidate.id,recordName:candidate.name,context:candidate.district,stage:candidate.promotionReview.status,verifiedCount:candidate.promotionReview.completedEvidence.length,totalGates:candidate.promotionReview.requiredEvidence.length,priority:p1Priority(candidate.id),...request})))
const editionTaskTemplates={
  itemEdition:{submissionType:'edition-locator',requiredFields:['series','volume','number','pageOrItem','sourceUrl'],instruction:{en:'Resolve the exact corpus, volume, item number, page and plate for this inscription edition packet.',kn:'ಈ ಶಾಸನ ಆವೃತ್ತಿ ಕಡತಕ್ಕೆ ನಿಖರ ಕಾರ್ಪಸ್, ಸಂಪುಟ, ಸಂಖ್ಯೆ, ಪುಟ ಮತ್ತು ಫಲಕವನ್ನು ನಿರ್ಧರಿಸಿ.'}},
  transcription:{submissionType:'line-transcription',requiredFields:['sourceId','lineNumbers','originalText','transliteration','editorNotes'],instruction:{en:'Capture or verify the line-by-line original text and transliteration from the item edition.',kn:'ವಸ್ತುಮಟ್ಟದ ಆವೃತ್ತಿಯಿಂದ ಸಾಲು-ಸಾಲಿನ ಮೂಲ ಪಾಠ ಮತ್ತು ಲಿಪ್ಯಂತರವನ್ನು ದಾಖಲಿಸಿ ಅಥವಾ ಪರಿಶೀಲಿಸಿ.'}},
  translation:{submissionType:'translation-review',requiredFields:['sourceTranslation','kannadaTranslation','englishSummary','reviewerAttestation'],instruction:{en:'Add or review the translation evidence, including independent Kannada review where a new translation is supplied.',kn:'ಹೊಸ ಅನುವಾದ ನೀಡಿದರೆ ಸ್ವತಂತ್ರ ಕನ್ನಡ ವಿಮರ್ಶೆ ಸೇರಿ ಅನುವಾದ ಸಾಕ್ಷ್ಯವನ್ನು ಸೇರಿಸಿ ಅಥವಾ ಪರಿಶೀಲಿಸಿ.'}},
  photographs:{submissionType:'photo-set',requiredFields:['imageUrl','creator','captureDate','license','depictedSurface'],instruction:{en:'Attach dated, licensed photographs or record why photographs are restricted or unavailable.',kn:'ದಿನಾಂಕಿತ, ಪರವಾನಗಿ ಹೊಂದಿದ ಚಿತ್ರಗಳನ್ನು ಜೋಡಿಸಿ ಅಥವಾ ಚಿತ್ರಗಳು ನಿರ್ಬಂಧಿತ/ಲಭ್ಯವಿಲ್ಲದ ಕಾರಣವನ್ನು ದಾಖಲಿಸಿ.'}},
  authorityCoordinate:{submissionType:'authority-coordinate',requiredFields:['latitude','longitude','authoritySource','precision','matchMethod'],instruction:{en:'Resolve the inscription or site coordinate against an authority source without copying an unverified map point into the public record.',kn:'ಪರಿಶೀಲಿಸದ ನಕ್ಷೆ ಬಿಂದುವನ್ನು ಸಾರ್ವಜನಿಕ ದಾಖಲೆಗೆ ನಕಲಿಸದೆ ಶಾಸನ ಅಥವಾ ತಾಣ ನಿರ್ದೇಶಾಂಕವನ್ನು ಪ್ರಾಧಿಕೃತ ಆಕರದೊಂದಿಗೆ ನಿರ್ಧರಿಸಿ.'}},
}
const editionTasks=atlasData.inscriptionEditions.flatMap(packet=>{
  const inscription=inscriptionById.get(packet.inscriptionId),place=placeById.get(inscription?.placeId),fields=Object.keys(editionTaskTemplates)
  return fields.filter(field=>packet.evidenceGates?.[field]?.status!=='verified').map(field=>({id:`${packet.id}:${field}`,domain:'epigraphy',recordId:packet.id,recordName:packet.name,context:place?.name||inscription?.name||{en:'Inscription edition packet',kn:'ಶಾಸನ ಆವೃತ್ತಿ ಕಡತ'},stage:'p2-edition-review',verifiedCount:fields.filter(gate=>packet.evidenceGates?.[gate]?.status==='verified').length,totalGates:fields.length,priority:4,field,currentStatus:packet.evidenceGates?.[field]?.status||'unresolved',...editionTaskTemplates[field]}))
})
const literatureTasks=atlasData.works.flatMap(work=>(work.reviewWorkflow?.evidenceRequests||[]).map(request=>({id:`${work.id}:${request.field}`,domain:'literature',recordId:work.id,recordName:work.name,context:work.creator,stage:work.reviewWorkflow.status,verifiedCount:work.reviewWorkflow.completedEvidence.length,totalGates:work.reviewWorkflow.requiredEvidence.length,priority:4,...request})))
const baseTasks=[...inscriptionTasks,...editionTasks,...literatureTasks]
const emptyAssignments={}

export default function EvidenceWorkflow({locale,communityUser}){
  const t=copy[locale],s=sprintCopy[locale],canManage=communityUser?.accountStatus==='approved'
  const [assignments,setAssignments]=useState(emptyAssignments),[query,setQuery]=useState(''),[domain,setDomain]=useState('all'),[field,setField]=useState('all'),[state,setState]=useState('all'),[priority,setPriority]=useState('all'),[visibleByColumn,setVisibleByColumn]=useState({}),[service,setService]=useState(canManage?'loading':'view-only'),[error,setError]=useState('')
  useEffect(()=>{let active=true;if(!canManage){setService('view-only');setAssignments(emptyAssignments);return}setService('loading');fetch(`${API_BASE}/api/evidence/assignments`,{credentials:'include'}).then(response=>response.ok?response.json():Promise.reject(new Error('Unable to load the permanent worklist.'))).then(data=>{if(!active)return;setAssignments(Object.fromEntries((data.assignments||[]).map(item=>[item.taskId,item])));setService('ready')}).catch(error=>{if(active){setService('offline');setError(error.message||'Unable to connect to the permanent evidence service.')}});return()=>{active=false}},[canManage])
  useEffect(()=>setVisibleByColumn({}),[query,domain,field,state,priority])
  const tasks=useMemo(()=>baseTasks.map(task=>({...task,status:assignments[task.id]?.status||'todo',assignee:assignments[task.id]?.assignee||'',due:assignments[task.id]?.due||''})),[assignments])
  const filtered=tasks.filter(task=>(domain==='all'||task.domain===domain)&&(field==='all'||task.field===field)&&(state==='all'||task.status===state)&&(priority==='all'||(priority==='p1'&&task.priority<4))&&(!query||JSON.stringify(task).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>a.priority-b.priority||a.recordId.localeCompare(b.recordId))
  const save=async(id,patch)=>{if(!canManage||service!=='ready')return;const previous=assignments[id]||{};const next={...previous,...patch,updatedAt:new Date().toISOString()};setAssignments(current=>({...current,[id]:next}));setError('');try{await fetch(`${API_BASE}/api/evidence/assignments/${encodeURIComponent(id)}`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)}).then(response=>response.ok?response.json():response.json().then(body=>Promise.reject(new Error(body.error||'Unable to save assignment.'))))}catch(error){setAssignments(current=>({...current,[id]:previous}));setError(error.message)}}
  const focusPromotionPacket=candidate=>{setDomain('epigraphy');setPriority('p1');setField('all');setState('all');setQuery(candidate.id);requestAnimationFrame(()=>document.querySelector('.evidence-toolbar')?.scrollIntoView({behavior:'smooth',block:'start'}))}
  const counts={progress:tasks.filter(task=>task.status==='in-progress').length,review:tasks.filter(task=>task.status==='awaiting-review').length}
  const statusNote=service==='offline'?t.offline:canManage?t.permanent:t.permanent
  return <main className="evidence-page portal-page" id="evidence"><header className="evidence-hero"><p className="eyebrow">{t.eyebrow}</p><h2>{t.title}</h2><p>{t.intro}</p><div className={`evidence-local-note ${service==='offline'?'offline':''}`}>{statusNote}</div>{error&&<p className="evidence-error" role="alert">{error}</p>}</header>
    {service==='loading'?<p className="evidence-loading">{t.loading}</p>:<><section className="evidence-procedure"><h3>{t.procedure}</h3><ol>{t.steps.map(step=><li key={step}>{step}</li>)}</ol><div><a href="#epigraphy">{t.openEpigraphy}</a><a href="#literature">{t.openLiterature}</a><a href="#community">{t.contribute}</a></div></section>
    <section className="evidence-promotion-sprint" aria-labelledby="promotion-sprint-title"><header><p className="eyebrow">{s.eyebrow}</p><h3 id="promotion-sprint-title">{s.title}</h3><p>{s.intro}</p></header><div className="promotion-packet-grid">{p1PromotionCandidates.map(candidate=>{const review=candidate.promotionReview,completed=new Set(review.completedEvidence),percent=Math.round(completed.size/review.requiredEvidence.length*100);return <article className={`promotion-packet priority-${p1Priority(candidate.id)}`} key={candidate.id}><div className="promotion-packet-heading"><div><small>{primary(candidate.district,locale)}</small><h4>{primary(candidate.name,locale)}</h4></div><span>{completed.size}/{review.requiredEvidence.length}</span></div><p className="promotion-stage">{s.stage[review.status]||review.status}</p><div className="promotion-progress" role="progressbar" aria-label={`${primary(candidate.name,locale)} · ${s.gates}`} aria-valuemin="0" aria-valuemax="7" aria-valuenow={completed.size}><i style={{width:`${percent}%`}}></i></div><ul className="promotion-gates">{review.requiredEvidence.map(gate=><li className={completed.has(gate)?'complete':'blocked'} key={gate}><span aria-hidden="true">{completed.has(gate)?'✓':'○'}</span>{t.fields[gate]}<small>{completed.has(gate)?s.complete:s.blocked}</small></li>)}</ul><button onClick={()=>focusPromotionPacket(candidate)}>{s.openTasks} · {review.blockingEvidence.length}</button><code>{candidate.id}</code></article>})}</div></section>
    <section className="evidence-stats">{[[tasks.length,t.total],[candidates.length+atlasData.works.length,t.records],[counts.progress,t.inProgress],[counts.review,t.review]].map(([value,label])=><article key={label}><b>{value}</b><span>{label}</span></article>)}</section>
    <section className="evidence-toolbar"><input aria-label={t.search} value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.search}/><select aria-label={t.allDomains} value={domain} onChange={event=>{setDomain(event.target.value);setField('all')}}><option value="all">{t.allDomains}</option><option value="epigraphy">{t.epigraphy}</option><option value="literature">{t.literature}</option></select><select aria-label={t.allFields} value={field} onChange={event=>setField(event.target.value)}><option value="all">{t.allFields}</option>{Object.entries(t.fields).filter(([value])=>domain==='all'||(domain==='literature'?literatureTasks:inscriptionTasks).some(task=>task.field===value)).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select aria-label={t.allStates} value={state} onChange={event=>setState(event.target.value)}><option value="all">{t.allStates}</option>{Object.entries(t.states).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select aria-label={t.allPriorities} value={priority} onChange={event=>setPriority(event.target.value)}><option value="all">{t.allPriorities}</option><option value="p1">{t.p1Only}</option></select></section>
    <section className="evidence-board">{Object.keys(t.states).map(column=>{const columnTasks=filtered.filter(task=>task.status===column),visible=columnTasks.slice(0,visibleByColumn[column]||INITIAL_VISIBLE),remaining=columnTasks.length-visible.length;return <div className={`evidence-column ${column}`} key={column}><header><h3>{t.states[column]}</h3><b>{columnTasks.length}</b></header>{visible.map(task=><article className={`evidence-task ${task.domain}`} key={task.id}><small>{task.priority<4&&<span className="evidence-priority">{t.p1Label} · </span>}{t[task.domain]} · {primary(task.context,locale)} · {task.verifiedCount}/{task.totalGates}</small><h4>{primary(task.recordName,locale)}</h4><strong>{t.fields[task.field]}</strong><p>{primary(task.instruction,locale)}</p><details><summary>{locale==='kn'?'ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳು':'Required fields'}</summary><code>{task.requiredFields.join(' · ')}</code></details><label>{locale==='kn'?'ಸ್ಥಿತಿ':'Status'}<select disabled={!canManage||service!=='ready'} value={task.status} onChange={event=>save(task.id,{status:event.target.value})}>{Object.entries(t.states).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>{t.assignee}<input disabled={!canManage||service!=='ready'} value={task.assignee} onChange={event=>save(task.id,{assignee:event.target.value})} placeholder={t.unassigned}/></label><label>{t.due}<input disabled={!canManage||service!=='ready'} type="date" value={task.due} onChange={event=>save(task.id,{due:event.target.value})}/></label><code>{task.recordId}</code></article>)}{remaining>0&&<button className="evidence-load-more" onClick={()=>setVisibleByColumn(current=>({...current,[column]:(current[column]||INITIAL_VISIBLE)+INITIAL_VISIBLE}))}>{t.loadMore} · {remaining}</button>}{columnTasks.length>0&&remaining===0&&<small className="evidence-all-shown">{t.allShown}</small>}</div>})}</section></>}
  </main>
}
