import { useMemo, useState } from 'react'
import { atlasData } from './data/atlas'

const STORAGE_KEY='karnataka-atlas-evidence-assignments-v0.19.1'
const primary=(value,locale)=>value?.[locale]||value?.en||value?.kn||''
const copy={
  kn:{eyebrow:'Atlas v0.19 · ಪ್ರಕಟಣೆ ಸಿದ್ಧತೆ',title:'ಮಾನವ ಸಾಕ್ಷ್ಯ ಕಾರ್ಯವಿಧಾನ',intro:'ಶಾಸನ ಅಭ್ಯರ್ಥಿಗಳನ್ನು ಪ್ರಕಟಿಸುವ ಮೊದಲು ಬೇಕಾದ ಕ್ಷೇತ್ರಕಾರ್ಯ, ಪಠ್ಯ ಪರಿಶೀಲನೆ ಮತ್ತು ಸ್ವತಂತ್ರ ಕನ್ನಡ ವಿಮರ್ಶೆಯನ್ನು ಒಂದೇ ಕಾರ್ಯಪಟ್ಟಿಯಲ್ಲಿ ನಿರ್ವಹಿಸಿ.',local:'ಈ ನಿಯೋಜನೆಗಳು ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಮಾತ್ರ ಉಳಿಯುತ್ತವೆ. ತಂಡಕ್ಕೆ ಹಸ್ತಾಂತರಿಸಲು JSON ರಫ್ತು ಮಾಡಿ; ಲೈವ್ ಸೇವೆ ಆರಂಭವಾದ ನಂತರ ಇದೇ ಕಾರ್ಯವಿಧಾನವನ್ನು MariaDBಗೆ ಸ್ಥಳಾಂತರಿಸಲಾಗುತ್ತದೆ.',total:'ಒಟ್ಟು ಬಾಕಿ ಕಾರ್ಯಗಳು',candidates:'ಅಭ್ಯರ್ಥಿಗಳು',inProgress:'ಪ್ರಗತಿಯಲ್ಲಿವೆ',review:'ವಿಮರ್ಶೆಗೆ ಕಾಯುತ್ತಿವೆ',search:'ಅಭ್ಯರ್ಥಿ, ಜಿಲ್ಲೆ ಅಥವಾ ಕಾರ್ಯ ಹುಡುಕಿ',allFields:'ಎಲ್ಲ ಸಾಕ್ಷ್ಯ ವಿಧಗಳು',allStates:'ಎಲ್ಲ ಕಾರ್ಯ ಸ್ಥಿತಿಗಳು',export:'ಕಾರ್ಯಪಟ್ಟಿ JSON ರಫ್ತು',assignee:'ನಿಯೋಜಿತ ವ್ಯಕ್ತಿ / ಸಂಸ್ಥೆ',due:'ಗಡುವು',unassigned:'ಇನ್ನೂ ನಿಯೋಜಿಸಿಲ್ಲ',procedure:'ಕಾರ್ಯ ನಿರ್ವಹಣಾ ಕ್ರಮ',steps:['ಅಭ್ಯರ್ಥಿ ಮತ್ತು ಒಂದು ಸಾಕ್ಷ್ಯ ಕಾರ್ಯವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ; ಹೊಣೆಗಾರ ವ್ಯಕ್ತಿ ಅಥವಾ ಸಂಸ್ಥೆಯನ್ನು ನಿಯೋಜಿಸಿ.','ಕಾರ್ಯಪಟ್ಟಿಯಲ್ಲಿ ಕೇಳಿರುವ ಕನಿಷ್ಠ ಕ್ಷೇತ್ರಗಳೊಂದಿಗೆ ಆಕರ, ಪುಟ/ಫಲಕ, ನಿರ್ದೇಶಾಂಕ ಅಥವಾ ಚಿತ್ರಗಳನ್ನು ಸಂಗ್ರಹಿಸಿ.','ಕೊಡುಗೆ ಪುಟದಲ್ಲಿ ಅಭ್ಯರ್ಥಿಯ ಸ್ಥಿರ IDಗೆ ಸಾಕ್ಷ್ಯವನ್ನು ಸಲ್ಲಿಸಿ; ಮೂಲ ಸಂಶೋಧಕ ತನ್ನದೇ ಸಲ್ಲಿಕೆಯನ್ನು ಅನುಮೋದಿಸಬಾರದು.','ನೇಮಕಗೊಂಡ ಪರಿಶೀಲಕರು ಆಕರ, ಗುರುತು, ಪರವಾನಗಿ ಮತ್ತು ಕನ್ನಡ ಅನುವಾದ ತಪಾಸಣೆಗಳನ್ನು ದಾಖಲಿಸುತ್ತಾರೆ.','ಎಲ್ಲ ಏಳು ಹಂತಗಳು ಪರಿಶೀಲಿತವಾದಾಗ ಮಾತ್ರ ಅಭ್ಯರ್ಥಿಯನ್ನು ಸಾರ್ವಜನಿಕ ಶಾಸನ ದಾಖಲೆಯಾಗಿ ಪ್ರಕಟಿಸಿ.'],openEpigraphy:'ಶಾಸನ ಸಂಶೋಧನೆ ತೆರೆಯಿರಿ',contribute:'ಸಾಕ್ಷ್ಯ ಸಲ್ಲಿಸಿ',states:{todo:'ಮಾಡಬೇಕಿದೆ','in-progress':'ಪ್ರಗತಿಯಲ್ಲಿದೆ','awaiting-review':'ವಿಮರ್ಶೆಗೆ ಕಾಯುತ್ತಿದೆ',blocked:'ತಡೆಗೊಂಡಿದೆ',complete:'ಪೂರ್ಣಗೊಂಡಿದೆ'},fields:{itemEdition:'ಪ್ರತ್ಯೇಕ ಆವೃತ್ತಿ',coordinates:'ಅಧಿಕೃತ ನಿರ್ದೇಶಾಂಕ',transcription:'ಸಾಲು-ಸಾಲಿನ ಪಾಠ',translation:'ಸ್ವತಂತ್ರ ಕನ್ನಡ ವಿಮರ್ಶೆ',presentCondition:'ದಿನಾಂಕಿತ ಸ್ಥಿತಿ',authority:'ಸಂರಕ್ಷಣಾ ಪ್ರಾಧಿಕಾರ',photographs:'ಪರವಾನಗಿ ಚಿತ್ರಗಳು'}},
  en:{eyebrow:'Atlas v0.19 · Publication readiness',title:'Human evidence workflow',intro:'Manage the fieldwork, text verification and independent Kannada review required before inscription candidates can be published.',local:'Assignments are stored only in this browser. Export JSON for team handoff; the same workflow can move to MariaDB when the live service is deployed.',total:'Outstanding tasks',candidates:'Candidates',inProgress:'In progress',review:'Awaiting review',search:'Search candidate, district or task',allFields:'All evidence types',allStates:'All task states',export:'Export worklist JSON',assignee:'Assigned person / institution',due:'Due date',unassigned:'Unassigned',procedure:'Operating procedure',steps:['Select a candidate and one evidence task; assign a responsible person or institution.','Collect the source, page or plate, coordinate or photograph with every minimum field listed in the request.','Submit the evidence against the candidate stable ID on the Contribute page; researchers cannot approve their own submission.','An appointed reviewer records source, identity, licence and Kannada translation checks.','Promote the candidate only after all seven evidence gates are verified.'],openEpigraphy:'Open epigraphy research',contribute:'Submit evidence',states:{todo:'To do','in-progress':'In progress','awaiting-review':'Awaiting review',blocked:'Blocked',complete:'Complete'},fields:{itemEdition:'Item edition',coordinates:'Authority coordinate',transcription:'Line transcription',translation:'Independent Kannada review',presentCondition:'Dated condition',authority:'Protection authority',photographs:'Licensed photographs'}}
}

const loadAssignments=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}}
const candidates=atlasData.inscriptionAudits.flatMap(audit=>(audit.priorityCandidates||[]).map(candidate=>({...candidate,district:audit.district})))
const baseTasks=candidates.flatMap(candidate=>(candidate.promotionReview?.evidenceRequests||[]).map(request=>({id:`${candidate.id}:${request.field}`,candidateId:candidate.id,candidateName:candidate.name,district:candidate.district,stage:candidate.promotionReview.status,verifiedCount:candidate.promotionReview.completedEvidence.length,totalGates:candidate.promotionReview.requiredEvidence.length,...request})))

export default function EvidenceWorkflow({locale}){
  const t=copy[locale],[assignments,setAssignments]=useState(loadAssignments),[query,setQuery]=useState(''),[field,setField]=useState('all'),[state,setState]=useState('all')
  const tasks=useMemo(()=>baseTasks.map(task=>({...task,status:assignments[task.id]?.status||'todo',assignee:assignments[task.id]?.assignee||'',due:assignments[task.id]?.due||''})),[assignments])
  const filtered=tasks.filter(task=>(field==='all'||task.field===field)&&(state==='all'||task.status===state)&&(!query||JSON.stringify(task).toLowerCase().includes(query.toLowerCase())))
  const save=(id,patch)=>setAssignments(current=>{const next={...current,[id]:{...current[id],...patch,updatedAt:new Date().toISOString()}};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));return next})
  const exportWorklist=()=>{const payload={schemaVersion:atlasData.meta.schemaVersion,exportedAt:new Date().toISOString(),storageMode:'browser-local-handoff',procedure:t.steps,tasks};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='atlas-v0.19-human-evidence-workflow.json';link.click();URL.revokeObjectURL(url)}
  const counts={progress:tasks.filter(task=>task.status==='in-progress').length,review:tasks.filter(task=>task.status==='awaiting-review').length}
  return <main className="evidence-page portal-page" id="evidence"><header className="evidence-hero"><p className="eyebrow">{t.eyebrow}</p><h2>{t.title}</h2><p>{t.intro}</p><div className="evidence-local-note">{t.local}</div></header>
    <section className="evidence-procedure"><h3>{t.procedure}</h3><ol>{t.steps.map(step=><li key={step}>{step}</li>)}</ol><div><a href="#epigraphy">{t.openEpigraphy}</a><a href="#community">{t.contribute}</a></div></section>
    <section className="evidence-stats">{[[tasks.length,t.total],[candidates.length,t.candidates],[counts.progress,t.inProgress],[counts.review,t.review]].map(([value,label])=><article key={label}><b>{value}</b><span>{label}</span></article>)}</section>
    <section className="evidence-toolbar"><input aria-label={t.search} value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.search}/><select aria-label={t.allFields} value={field} onChange={event=>setField(event.target.value)}><option value="all">{t.allFields}</option>{Object.entries(t.fields).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select aria-label={t.allStates} value={state} onChange={event=>setState(event.target.value)}><option value="all">{t.allStates}</option>{Object.entries(t.states).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><button onClick={exportWorklist}>{t.export}</button></section>
    <section className="evidence-board">{Object.keys(t.states).map(column=><div className={`evidence-column ${column}`} key={column}><header><h3>{t.states[column]}</h3><b>{filtered.filter(task=>task.status===column).length}</b></header>{filtered.filter(task=>task.status===column).map(task=><article className="evidence-task" key={task.id}><small>{primary(task.district,locale)} · {task.verifiedCount}/{task.totalGates}</small><h4>{primary(task.candidateName,locale)}</h4><strong>{t.fields[task.field]}</strong><p>{primary(task.instruction,locale)}</p><details><summary>{locale==='kn'?'ಅಗತ್ಯ ಕ್ಷೇತ್ರಗಳು':'Required fields'}</summary><code>{task.requiredFields.join(' · ')}</code></details><label>{locale==='kn'?'ಸ್ಥಿತಿ':'Status'}<select value={task.status} onChange={event=>save(task.id,{status:event.target.value})}>{Object.entries(t.states).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>{t.assignee}<input value={task.assignee} onChange={event=>save(task.id,{assignee:event.target.value})} placeholder={t.unassigned}/></label><label>{t.due}<input type="date" value={task.due} onChange={event=>save(task.id,{due:event.target.value})}/></label><code>{task.candidateId}</code></article>)}</div>)}</section>
  </main>
}
