export const messages = {
  kn: {
    digitalAtlas:'ಡಿಜಿಟಲ್ ಐತಿಹಾಸಿಕ ಭೂಪಟ', appTitle:'ಕರ್ನಾಟಕ ಇತಿಹಾಸ ಭೂಪಟ', appSubtitle:'Karnataka Kingdoms · Digital Historical Atlas', atlas:'ಭೂಪಟ', research:'ಸಂಶೋಧನೆ', admin:'ಸಂಶೋಧಕರ ನಿರ್ವಹಣೆ', districtHeritagePage:'ಜಿಲ್ಲಾ ಪರಂಪರೆ', inscriptionPage:'ಶಾಸನಗಳು', primaryNavigation:'ಮುಖ್ಯ ವಿಭಾಗಗಳು', researchPageIntro:'ಈ ಭೂಪಟದ ದತ್ತಾಂಶ ಮಾದರಿ, ಸಾಕ್ಷ್ಯ ವಿಧಾನ, ಭಾಷಾ ವಿನ್ಯಾಸ ಮತ್ತು ಪ್ರಕಟಣಾ ಕ್ರಮದ ಪರಿಚಯ.',
    searchKingdoms:'ಸಾಮ್ರಾಜ್ಯಗಳನ್ನು ಹುಡುಕಿ', searchPlaceholder:'ಸಾಮ್ರಾಜ್ಯ, ರಾಜಧಾನಿ…', kingdomsIn:'ಈ ವರ್ಷದಲ್ಲಿನ ಸಾಮ್ರಾಜ್ಯಗಳು', noKingdom:'ಈ ವರ್ಷಕ್ಕೆ ಹೊಂದುವ ಸಾಮ್ರಾಜ್ಯ ಮಾದರಿ ದತ್ತಾಂಶದಲ್ಲಿಲ್ಲ.', mapLayers:'ಭೂಪಟ ಪದರಗಳು', boundaries:'ಪುನರ್-ರಚಿತ ಗಡಿಗಳು', inscriptions:'ಶಾಸನಗಳು', modernMap:'ಆಧುನಿಕ ಮೂಲಭೂಪಟ',
    historicalYear:'ಐತಿಹಾಸಿಕ ವರ್ಷ', inscription:'ಶಾಸನ', schematicExtent:'ಅಂದಾಜು ಐತಿಹಾಸಿಕ ವ್ಯಾಪ್ತಿ', stableId:'ಸ್ಥಿರ ID', capital:'ರಾಜಧಾನಿ', rulers:'ತಿಳಿದಿರುವ ಅರಸರು', boundaryPrecision:'ಗಡಿ ನಿಖರತೆ', literature:'ಸಾಹಿತ್ಯಿಕ ಸಂದರ್ಭ', noLiterature:'ಸಂಶೋಧನಾ ದತ್ತಾಂಶ ಬೆಳೆದಂತೆ ಸಾಹಿತ್ಯ ಕೃತಿಗಳು ಮತ್ತು ಹಸ್ತಪ್ರತಿ ಕೊಂಡಿಗಳನ್ನು ಸೇರಿಸಬಹುದು.', openSanchaya:'ಸಂಚಯ ತೆರೆಯಿರಿ ↗', sources:'ಆಕರಗಳು', noSources:'ಇನ್ನೂ ಯಾವುದೇ ಉಲ್ಲೇಖಗಳನ್ನು ಜೋಡಿಸಿಲ್ಲ.',
    linkedResearch:'ಸಂಯೋಜಿತ ಸಂಶೋಧನೆಗಾಗಿ', researchTitle:'ಒಂದು ಕಾಲರೇಖೆ. ಹಲವು ಸಾಕ್ಷ್ಯ ರೂಪಗಳು.', openWorkspace:'ಸ್ಥಳೀಯ ಸಂಶೋಧನಾ ಕಾರ್ಯಕ್ಷೇತ್ರ ತೆರೆಯಿರಿ →', staticFirst:'ಸ್ಥಿರ-ಮೊದಲ ವಿನ್ಯಾಸ · GitHub Pages ಗಾಗಿ', switchLanguage:'English', languageLabel:'ಭಾಷೆ', ce:'ಕ್ರಿ.ಶ.', yearPrecision:'ವರ್ಷ',
    cards:[['ಸಾಮಾನ್ಯೀಕೃತ ದಾಖಲೆಗಳು','ಸ್ಥಿರ IDಗಳು ರಾಜ್ಯಗಳು, ವ್ಯಕ್ತಿಗಳು, ಸ್ಥಳಗಳು, ಶಾಸನಗಳು, ಕೃತಿಗಳು ಮತ್ತು ಆಕರಗಳನ್ನು ಜೋಡಿಸುತ್ತವೆ.'],['ಸಾಕ್ಷ್ಯ ಮತ್ತು ನಿಖರತೆ','ಪ್ರತಿ ದಾಖಲೆಗೆ ಉಲ್ಲೇಖ, ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ, ದಿನಾಂಕ ಮತ್ತು ಭೌಗೋಳಿಕ ನಿಖರತೆ ಇರಬಹುದು.'],['ದ್ವಿಭಾಷಾ ವಿನ್ಯಾಸ','ಕನ್ನಡ ಪ್ರಾಥಮಿಕ; ಇಂಗ್ಲಿಷ್ ಪೂರಕ ಸಂಶೋಧನಾ ಭಾಷೆ.'],['ಸ್ಥಿರ ಪ್ರಕಟಣೆ','ಸಾರ್ವಜನಿಕ GitHub Pages ತಾಣವು ಪರಿಶೀಲಿತ, ಓದಲು-ಮಾತ್ರದ ಸಂಶೋಧನಾ ಆವೃತ್ತಿಯನ್ನು ಒದಗಿಸುತ್ತದೆ; ಸಂಪಾದನೆ ಮತ್ತು ದತ್ತಾಂಶ ನಿರ್ವಹಣೆ ನಿರ್ವಾಹಕ ಕಾರ್ಯಕ್ಷೇತ್ರದಲ್ಲಿದೆ.'],['ಜೈಜ್ಞಾನ ಶಾಸನಸಂಪುಟಗಳು','ಎಪಿಗ್ರಾಫಿಯಾ ಇಂಡಿಕಾ ಮತ್ತು ಎಪಿಗ್ರಾಫಿಯಾ ಕರ್ನಾಟಕದ ಸ್ಕ್ಯಾನ್‌ಗಳನ್ನು ಸಂಪುಟ ಮತ್ತು ಪುಟ ಹುಡುಕಾಟಕ್ಕೆ ಬಳಸಿ; OCR ಅನ್ನು ಪುಟದ ಚಿತ್ರದೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ.','https://archive.org/search?query=collection%3AJaiGyan+AND+title%3AEpigraphia'],['ಸರ್ವೆಂಟ್ಸ್ ಆಫ್ ನಾಲೆಜ್','ಎಪಿಗ್ರಾಫಿಯಾ ಕರ್ನಾಟಕದ ಸಂಪುಟ-ನಿರ್ದಿಷ್ಟ ಸ್ಕ್ಯಾನ್‌ಗಳು ಪುನರುತ್ಪಾದಿಸಬಹುದಾದ ದಾಖಲೆ ಮತ್ತು ಪುಟ ಉಲ್ಲೇಖಗಳಿಗೆ ಲಭ್ಯ.','https://archive.org/search?query=collection%3AServantsOfKnowledge+AND+title%3AEpigraphia']]
  },
  en: {
    digitalAtlas:'Digital Historical Atlas', appTitle:'Karnataka Historical Atlas', appSubtitle:'Karnataka Kingdoms · Digital Historical Atlas', atlas:'Atlas', research:'Research', admin:'Researcher admin', districtHeritagePage:'District heritage', inscriptionPage:'Inscriptions', primaryNavigation:'Primary sections', researchPageIntro:'An introduction to the atlas data model, evidence method, bilingual design and publishing workflow.',
    searchKingdoms:'Search kingdoms', searchPlaceholder:'Kingdom, capital…', kingdomsIn:'Kingdoms in', noKingdom:'No kingdom in the sample dataset matches this year.', mapLayers:'Map layers', boundaries:'Reconstructed boundaries', inscriptions:'Inscriptions', modernMap:'Modern basemap',
    historicalYear:'Historical year', inscription:'Inscription', schematicExtent:'Schematic historical extent', stableId:'Stable ID', capital:'Capital', rulers:'Known rulers', boundaryPrecision:'Boundary precision', literature:'Literature in context', noLiterature:'Literary works and manuscript links can be added as the research dataset grows.', openSanchaya:'Open Sanchaya ↗', sources:'Sources', noSources:'No citations have been attached yet.',
    linkedResearch:'Designed for linked research', researchTitle:'One timeline. Many forms of evidence.', openWorkspace:'Open local research workspace →', staticFirst:'Static-first · Built for GitHub Pages', switchLanguage:'ಕನ್ನಡ', languageLabel:'Language', ce:'CE', yearPrecision:'year',
    cards:[['Normalized records','Stable IDs connect polities, people, places, inscriptions, works and sources.'],['Evidence and precision','Every record can carry citations, review status, date precision and geographic precision.'],['Bilingual by design','Kannada is primary; English supports wider research use.'],['Static publishing','The public GitHub Pages build provides a reviewed, read-only research edition; editing and dataset management stay in the administrator workspace.'],['JaiGyan epigraphy corpora','Use Epigraphia Indica and Epigraphia Carnatica scans to locate volumes and pages; always verify OCR against the page image.','https://archive.org/search?query=collection%3AJaiGyan+AND+title%3AEpigraphia'],['ServantsOfKnowledge','Volume-specific Epigraphia Carnatica scans support reproducible item and printed-page citations.','https://archive.org/search?query=collection%3AServantsOfKnowledge+AND+title%3AEpigraphia']]
  }
}

Object.assign(messages.kn,{events:'ಐತಿಹಾಸಿಕ ಘಟನೆಗಳು',noEvents:'ಈ ವರ್ಷದ ಸಮೀಪ ಯಾವುದೇ ಆಯ್ದ ಘಟನೆ ಇಲ್ಲ.',karnatakaView:'ಕರ್ನಾಟಕ',indiaView:'ಭಾರತ',worldView:'ವಿಶ್ವ',mapScope:'ಭೂಪಟ ವ್ಯಾಪ್ತಿ',eventTypes:'ರಾಜ್ಯೋದಯ · ಶಾಸನ · ಯುದ್ಧ · ದಂಡಯಾತ್ರೆ · ರಾಯಭಾರ · ವ್ಯಾಪಾರಿ ಜಾಲ · ಪ್ರಜಾಸತ್ತಾತ್ಮಕ ಪರಿವರ್ತನೆ',participants:'ಸಂಬಂಧಿತ ರಾಜ್ಯಗಳು',people:'ಸಂಬಂಧಿತ ವ್ಯಕ್ತಿಗಳು',consequence:'ಪರಿಣಾಮ',returnKingdom:'ರಾಜ್ಯ ವಿವರಕ್ಕೆ ಹಿಂತಿರುಗಿ',overseasConnection:'ಭಾರತದಾಚೆಯ ಸಂಪರ್ಕ',destination:'ಗಮ್ಯಸ್ಥಾನ',modernCountries:'ಇಂದಿನ ದೇಶಗಳು',territorialControl:'ಭೂಪ್ರದೇಶದ ಆಳ್ವಿಕೆ',territorialReach:'ಭೂಪ್ರದೇಶ ಸಾಕ್ಷ್ಯ',activeTerritorialEvidence:'ಈ ವರ್ಷದ ಭೂಪ್ರದೇಶ ಸಾಕ್ಷ್ಯ',controlLevel:'ನಿಯಂತ್ರಣ',duration:'ಅವಧಿ',confidence:'ವಿಶ್ವಾಸ ಮಟ್ಟ',geographicPrecision:'ಭೌಗೋಳಿಕ ನಿಖರತೆ',outbound:'ಹೊರಮುಖ',inbound:'ಒಳಮುಖ',bidirectional:'ದ್ವಿಮುಖ',yes:'ಹೌದು',no:'ಇಲ್ಲ',reachRelations:{'merchant-guild-presence':'ವ್ಯಾಪಾರಿ ಸಂಘದ ಹಾಜರಾತಿ','overseas-commerce':'ಸಾಗರೋತ್ತರ ವಾಣಿಜ್ಯ','diplomacy-and-commerce':'ರಾಜತಾಂತ್ರಿಕತೆ ಮತ್ತು ವಾಣಿಜ್ಯ',diplomacy:'ರಾಜತಾಂತ್ರಿಕ ಸಂಪರ್ಕ'},territoryClasses:{'core-administered':'ಮೂಲ ಆಡಳಿತ ಪ್ರದೇಶ','tributary-influence':'ಕಪ್ಪಕಾಣಿಕೆ ಪ್ರಭಾವ','contested-zone':'ವಿವಾದಿತ ವಲಯ','temporary-occupation':'ತಾತ್ಕಾಲಿಕ ನಿಯಂತ್ರಣ','campaign-reach':'ದಂಡಯಾತ್ರೆಯ ತಲುಪುವಿಕೆ'},controlValues:{direct:'ನೇರ',indirect:'ಪರೋಕ್ಷ',disputed:'ವಿವಾದಿತ',temporary:'ತಾತ್ಕಾಲಿಕ',none:'ಭೂಆಳ್ವಿಕೆ ಇಲ್ಲ'},durationValues:{sustained:'ದೀರ್ಘಕಾಲಿಕ','multi-generational':'ಹಲವು ತಲೆಮಾರುಗಳು',intermittent:'ಮಧ್ಯಂತರ',brief:'ಅಲ್ಪಾವಧಿ',episodic:'ಘಟನಾತ್ಮಕ'},confidenceValues:{low:'ಕಡಿಮೆ',medium:'ಮಧ್ಯಮ',high:'ಹೆಚ್ಚು'}})
Object.assign(messages.en,{events:'Historical events',noEvents:'No selected event near this year.',karnatakaView:'Karnataka',indiaView:'India',worldView:'World',mapScope:'Map scope',eventTypes:'Foundations · inscriptions · battles · campaigns · embassies · merchant networks · democratic transition',participants:'Related polities',people:'Related people',consequence:'Consequence',returnKingdom:'Return to kingdom details',overseasConnection:'Connection beyond India',destination:'Destination',modernCountries:'Present-day countries',territorialControl:'Territorial control',territorialReach:'Territorial evidence',activeTerritorialEvidence:'Territorial evidence this year',controlLevel:'Control',duration:'Duration',confidence:'Confidence',geographicPrecision:'Geographic precision',outbound:'Outbound',inbound:'Inbound',bidirectional:'Bidirectional',yes:'Yes',no:'No',reachRelations:{'merchant-guild-presence':'Merchant-guild presence','overseas-commerce':'Overseas commerce','diplomacy-and-commerce':'Diplomacy and commerce',diplomacy:'Diplomacy'},territoryClasses:{'core-administered':'Core administration','tributary-influence':'Tributary influence','contested-zone':'Contested zone','temporary-occupation':'Temporary control','campaign-reach':'Campaign reach'},controlValues:{direct:'Direct',indirect:'Indirect',disputed:'Disputed',temporary:'Temporary',none:'No territorial control'},durationValues:{sustained:'Sustained','multi-generational':'Multi-generational',intermittent:'Intermittent',brief:'Brief',episodic:'Episodic'},confidenceValues:{low:'Low',medium:'Medium',high:'High'}})

Object.assign(messages.kn.reachRelations,{'diplomatic-visit-and-travel-account':'ರಾಜತಾಂತ್ರಿಕ ಭೇಟಿ ಮತ್ತು ಪ್ರವಾಸವಿವರಣೆ'})
Object.assign(messages.en.reachRelations,{'diplomatic-visit-and-travel-account':'Diplomatic visit and travel account'})
Object.assign(messages.kn,{historicalConnections:'ಐತಿಹಾಸಿಕ ಸಂಪರ್ಕಗಳು',connectionTypes:{trade:'ವ್ಯಾಪಾರ','trade-diplomacy':'ವ್ಯಾಪಾರ · ರಾಜತಾಂತ್ರಿಕತೆ',diplomacy:'ರಾಜತಾಂತ್ರಿಕತೆ','knowledge-diplomacy':'ಪ್ರವಾಸ · ಜ್ಞಾನ ವಿನಿಮಯ',military:'ಸೈನಿಕ ಸಂಪರ್ಕ',other:'ಇತರೆ ಸಂಪರ್ಕ'}})
Object.assign(messages.en,{historicalConnections:'Historical connections',connectionTypes:{trade:'Trade','trade-diplomacy':'Trade · diplomacy',diplomacy:'Diplomacy','knowledge-diplomacy':'Travel · knowledge exchange',military:'Military connection',other:'Other connection'}})
Object.assign(messages.kn,{selectDistrictMode:'ಜಿಲ್ಲೆ ಆಯ್ಕೆ ಮೋಡ್',selectDistrictModeNote:'ಇದನ್ನು ಆನ್ ಮಾಡಿದಾಗ ಮಾತ್ರ ಗಡಿ ಕ್ಲಿಕ್ ಆಯ್ಕೆ ಸಕ್ರಿಯವಾಗುತ್ತದೆ.',openCommunity:'ಸಮುದಾಯ ಪ್ರವೇಶ ತೆರೆಯಿರಿ'})
Object.assign(messages.en,{selectDistrictMode:'District selection mode',selectDistrictModeNote:'Boundary selection is enabled only when this is turned on.',openCommunity:'Open community access'})
Object.assign(messages.kn,{timelineStories:'ಕಾಲರೇಖೆಯ ಕಥಾಪಥಗಳು',searchTimeline:'ಕಾಲರೇಖೆ ಹುಡುಕಿ',searchTimelinePlaceholder:'ಅರಸು, ಕವಿ, ಯುದ್ಧ, ಕೃತಿ…',noTimelineStories:'ಈ ಆಯ್ಕೆಗೆ ದಾಖಲೆಗಳಿಲ್ಲ.',associatedCourt:'ಸಂಬಂಧಿತ ಅರಮನೆ/ರಾಜಧಾನಿ',timelineCategories:{all:'ಎಲ್ಲ',wars:'ಯುದ್ಧಗಳು',political:'ರಾಜಕೀಯ',connections:'ವ್ಯಾಪಾರ · ರಾಯಭಾರ',people:'ವ್ಯಕ್ತಿಗಳು',literature:'ಸಾಹಿತ್ಯ',inscriptions:'ಶಾಸನಗಳು',reigns:'ಆಳ್ವಿಕೆಗಳು',territory:'ಭೂವಿಸ್ತಾರ',culture:'ಕಲೆ · ಸಂಸ್ಕೃತಿ',history:'ಇತಿಹಾಸ'}})
Object.assign(messages.en,{timelineStories:'Timeline stories',searchTimeline:'Search timeline',searchTimelinePlaceholder:'Ruler, poet, war, work…',noTimelineStories:'No records match this selection.',associatedCourt:'Associated court/capital',timelineCategories:{all:'All',wars:'Wars',political:'Political',connections:'Trade · diplomacy',people:'People',literature:'Literature',inscriptions:'Inscriptions',reigns:'Reigns',territory:'Territory',culture:'Art · culture',history:'History'}})

Object.assign(messages.kn,{compareYears:'ಎರಡು ವರ್ಷಗಳನ್ನು ಹೋಲಿಸಿ',closeComparison:'ಹೋಲಿಕೆ ಮುಚ್ಚಿ',yearA:'ವರ್ಷ A',yearB:'ವರ್ಷ B',comparisonStories:'ಸಿದ್ಧ ಹೋಲಿಕೆ ಕಥೆಗಳು',badamiComparison:'ವಾತಾಪಿ: 618 → 655',rashtrakutaComparison:'ರಾಷ್ಟ್ರಕೂಟ: 753 → 850',hoysalaComparison:'ಹೊಯ್ಸಳ: 1187 → 1311',talikotaComparison:'ತಾಳಿಕೋಟೆ: 1520 → 1570',mysoreComparison:'ಮೈಸೂರು: 1787 → 1800',beforeLayer:'ಮೊದಲ ವರ್ಷದ ಸಾಕ್ಷ್ಯ',afterLayer:'ಎರಡನೇ ವರ್ಷದ ಬದಲಾವಣೆ',unchangedEvidence:'ಬದಲಾಗದ ಸಾಕ್ಷ್ಯ',comparisonHelp:'ಎರಡನೇ ವರ್ಷದ ಹೊಸ ಅಥವಾ ಬದಲಾಗಿದ ಸಾಕ್ಷ್ಯವನ್ನು ನೀಲಿ-ಹಸಿರು ಗೆರೆಯಲ್ಲಿ ತೋರಿಸಲಾಗಿದೆ.',researchPeriod:'ಸಂಶೋಧನಾ ಅವಧಿ'})
Object.assign(messages.en,{compareYears:'Compare two years',closeComparison:'Close comparison',yearA:'Year A',yearB:'Year B',comparisonStories:'Ready comparison stories',badamiComparison:'Vatapi: 618 → 655',rashtrakutaComparison:'Rashtrakuta: 753 → 850',hoysalaComparison:'Hoysala: 1187 → 1311',talikotaComparison:'Talikota: 1520 → 1570',mysoreComparison:'Mysore: 1787 → 1800',beforeLayer:'First-year evidence',afterLayer:'Second-year change',unchangedEvidence:'Unchanged evidence',comparisonHelp:'New or changed evidence in the second year is outlined in teal.',researchPeriod:'Research period'})

Object.assign(messages.kn,{culturalHeritage:'ಸ್ಮಾರಕಗಳು · ಕಲೆ · ಸಂಸ್ಕೃತಿ',continuity:'ನಿರಂತರತೆ',culturalPlace:'ಸ್ಥಳ',cultureCategories:{architecture:'ಸ್ಮಾರಕ ಮತ್ತು ವಾಸ್ತುಶಿಲ್ಪ','visual-art':'ದೃಶ್ಯಕಲೆ',literature:'ಸಾಹಿತ್ಯ',performance:'ಪ್ರದರ್ಶನ ಕಲೆ',music:'ಸಂಗೀತ',celebration:'ಹಬ್ಬ ಮತ್ತು ಆಚರಣೆ','religious-tradition':'ಧಾರ್ಮಿಕ ಪರಂಪರೆ',craft:'ಕರಕುಶಲ','games-sports':'ಆಟಗಳು ಮತ್ತು ಕ್ರೀಡೆಗಳು'},continuityValues:{historic:'ಐತಿಹಾಸಿಕ ಆಚರಣೆ','continuing-practice':'ಇಂದಿಗೂ ಜೀವಂತ ಪರಂಪರೆ','material-survival':'ಭೌತಿಕ ಪರಂಪರೆ ಉಳಿದಿದೆ',revived:'ಪುನರುಜ್ಜೀವಿತ ಪರಂಪರೆ',unknown:'ತಿಳಿದಿಲ್ಲ'}})
Object.assign(messages.en,{culturalHeritage:'Monuments · art · culture',continuity:'Continuity',culturalPlace:'Place',cultureCategories:{architecture:'Monument & architecture','visual-art':'Visual art',literature:'Literature',performance:'Performance',music:'Music',celebration:'Festival & celebration','religious-tradition':'Religious tradition',craft:'Craft','games-sports':'Games & sports'},continuityValues:{historic:'Historic practice','continuing-practice':'Living tradition','material-survival':'Material heritage survives',revived:'Revived tradition',unknown:'Unknown'}})

Object.assign(messages.kn,{deepHistoryTitle:'ಪ್ರಾಚೀನ ಕಾಲಕ್ರಮಗಳ ಆಕರ ವೀಕ್ಷಣೆ',deepHistoryIntro:'ರಾಜಕೀಯ ಭೂಪಟದ ದಿನಾಂಕಗಳಿಂದ ಪ್ರತ್ಯೇಕವಾಗಿ ಪಠ್ಯ, ಪುರಾತತ್ತ್ವ ಮತ್ತು ಸಾಂಪ್ರದಾಯಿಕ ಕಾಲಕ್ರಮಗಳನ್ನು ಹೋಲಿಸಿ.',sourceChronology:'ಆಕರ ಕಾಲಕ್ರಮ',interpretiveChronology:'ವ್ಯಾಖ್ಯಾನಾತ್ಮಕ · ಪ್ರದೇಶಮಟ್ಟ',openSource:'ಆಕರ ತೆರೆಯಿರಿ ↗',districtAuditTitle:'ಜಿಲ್ಲಾವಾರು ಪರಂಪರೆ ಪರಿಶೀಲನೆ',districtAuditIntro:'31 ಜಿಲ್ಲೆಗಳ ಸಂಶೋಧನಾ ವ್ಯಾಪ್ತಿ: ಕಂಡುಬಂದ ಅಭ್ಯರ್ಥಿಗಳು ಮತ್ತು ಇನ್ನೂ ಪರಿಶೀಲಿಸಬೇಕಾದ ವರ್ಗಗಳು.',searchDistricts:'ಜಿಲ್ಲೆ ಅಥವಾ ತಾಣ ಹುಡುಕಿ',allCategories:'ಎಲ್ಲ ವರ್ಗಗಳು',seeded:'ಆರಂಭಿಕ ಅಭ್ಯರ್ಥಿಗಳು',unassessed:'ಪರಿಶೀಲಿಸಿಲ್ಲ',auditCandidate:'ಪರಿಶೀಲಿಸಬೇಕಾದ ಅಭ್ಯರ್ಥಿ',districtsShown:'ಜಿಲ್ಲೆಗಳು',heritageCategoryLabels:{temple:'ದೇವಾಲಯ','coastal-temple':'ಕರಾವಳಿ ದೇವಾಲಯ',basadi:'ಬಸದಿ',dargah:'ದರ್ಗಾ',church:'ಚರ್ಚ್',monastery:'ಮಠ','fort':'ಕೋಟೆ','palace-civic-architecture':'ಅರಮನೆ ಮತ್ತು ನಾಗರಿಕ ವಾಸ್ತು','colonial-architecture':'ವಸಾಹತು ಕಾಲದ ವಾಸ್ತು','archaeological-landscape':'ಪುರಾತತ್ತ್ವ ಭೂದೃಶ್ಯ','modern-heritage':'ಆಧುನಿಕ ಪರಂಪರೆ'}})
Object.assign(messages.en,{deepHistoryTitle:'Deep-history chronology browser',deepHistoryIntro:'Compare textual, archaeological, and traditional chronologies separately from the dated political map.',sourceChronology:'Source chronology',interpretiveChronology:'Interpretive · region-level',openSource:'Open source ↗',districtAuditTitle:'District-by-district heritage audit',districtAuditIntro:'Research coverage across all 31 districts: seeded candidates and categories still awaiting assessment.',searchDistricts:'Search district or site',allCategories:'All categories',seeded:'Seeded',unassessed:'Unassessed',auditCandidate:'Candidate for verification',districtsShown:'districts',heritageCategoryLabels:{temple:'Temple','coastal-temple':'Coastal temple',basadi:'Basadi',dargah:'Dargah',church:'Church',monastery:'Monastery / matha',fort:'Fort','palace-civic-architecture':'Palace & civic architecture','colonial-architecture':'Colonial architecture','archaeological-landscape':'Archaeological landscape','modern-heritage':'Modern heritage'}})

Object.assign(messages.kn,{coordinates:'ನಿರ್ದೇಶಾಂಕಗಳು',constructionPhase:'ನಿರ್ಮಾಣ ಹಂತ',protectionStatus:'ರಕ್ಷಣಾ ಸ್ಥಿತಿ',managingAuthority:'ನಿರ್ವಹಣಾ ಪ್ರಾಧಿಕಾರ',photoSource:'ಚಿತ್ರದ ಮೂಲ',researchPending:'ಸಂಶೋಧನೆ ಬಾಕಿ',verificationLabels:{'research-pending':'ಸಂಶೋಧನೆ ಬಾಕಿ',identified:'ಗುರುತಿಸಲಾಗಿದೆ','partially-verified':'ಭಾಗಶಃ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',verified:'ಪರಿಶೀಲಿಸಲಾಗಿದೆ'}})
Object.assign(messages.en,{coordinates:'Coordinates',constructionPhase:'Construction phase',protectionStatus:'Protection status',managingAuthority:'Managing authority',photoSource:'Photo source',researchPending:'Research pending',verificationLabels:{'research-pending':'Research pending',identified:'Identified','partially-verified':'Partially verified',verified:'Verified'}})
Object.assign(messages.kn,{candidatesResolved:'ಅಭ್ಯರ್ಥಿಗಳಿಗೆ ಆಕರಗಳನ್ನು ಜೋಡಿಸಲಾಗಿದೆ'})
Object.assign(messages.en,{candidatesResolved:'candidates linked to evidence'})
Object.assign(messages.kn,{districtBoundaries:'ಜಿಲ್ಲಾ ಗಡಿಗಳು',districtBoundarySource:'ಭಾರತ್‌ಮ್ಯಾಪ್ಸ್ ಗಡಿ ಆಕರ',heritageCandidates:'ಪರಂಪರೆ ಅಭ್ಯರ್ಥಿ ತಾಣಗಳು',allDistricts:'ಎಲ್ಲ ಜಿಲ್ಲೆಗಳು',allHeritageCategories:'ಎಲ್ಲ ಪರಂಪರೆ ವರ್ಗಗಳು',mapHeritageFilters:'ಜಿಲ್ಲಾವಾರು ಪರಂಪರೆ ನಕ್ಷೆ',heritageAuthorityFilter:'ಪರಂಪರೆ ಪ್ರಾಧಿಕಾರ',heritageAuthorityLabels:{all:'ಎಲ್ಲ ಪ್ರಾಧಿಕಾರಗಳು',unesco:'ಯುನೆಸ್ಕೋ ವಿಶ್ವ ಪರಂಪರೆ',asi:'ASI ಸಂರಕ್ಷಿತ',state:'ರಾಜ್ಯ ಪರಂಪರೆ',research:'ಸಂಶೋಧನಾ ಮುನ್ನಡೆ'},candidateLocations:'ನಕ್ಷೆಗೊಳಿಸಿದ ಅಭ್ಯರ್ಥಿಗಳು',verificationChecks:'ಸಾಕ್ಷ್ಯ ಪರಿಶೀಲನೆಗಳು',photoLicenceCheck:'ಚಿತ್ರ ಪರವಾನಗಿ',protectionRegisterCheck:'ರಕ್ಷಣಾ ಪಟ್ಟಿ',managerCheck:'ನಿರ್ವಹಣಾ ಪ್ರಾಧಿಕಾರ',conditionCheck:'ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ'})
Object.assign(messages.en,{districtBoundaries:'District boundaries',districtBoundarySource:'BharatMaps boundary source',heritageCandidates:'Heritage candidate sites',allDistricts:'All districts',allHeritageCategories:'All heritage categories',mapHeritageFilters:'District heritage map',heritageAuthorityFilter:'Heritage authority',heritageAuthorityLabels:{all:'All authorities',unesco:'UNESCO World Heritage',asi:'ASI protected',state:'State heritage',research:'Research lead'},candidateLocations:'mapped candidates',verificationChecks:'Evidence checks',photoLicenceCheck:'Photo licence',protectionRegisterCheck:'Protection register',managerCheck:'Managing authority',conditionCheck:'Present condition'})
Object.assign(messages.kn,{mapTheme:'ಭೂಪಟ ಶೈಲಿ',modernTheme:'ಆಧುನಿಕ',historicalTheme:'ಐತಿಹಾಸಿಕ ಕಾಗದ',mapThemeNote:'ಇದು ದೃಶ್ಯ ಶೈಲಿ ಮಾತ್ರ; ಐತಿಹಾಸಿಕ ದತ್ತಾಂಶ ಮತ್ತು ಗಡಿಗಳು ಬದಲಾಗುವುದಿಲ್ಲ.'})
Object.assign(messages.en,{mapTheme:'Map style',modernTheme:'Modern',historicalTheme:'Historical parchment',mapThemeNote:'Visual style only; historical data and boundaries remain unchanged.'})
Object.assign(messages.kn,{literaryTimeline:'ಸಾಹಿತ್ಯ ಕಾಲರೇಖೆ',activeLiteraryMilestones:'ಈ ವರ್ಷದಲ್ಲಿ ಸಕ್ರಿಯವಾಗಿರುವ ರಾಜ್ಯಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ ಕವಿಗಳು, ಲೇಖಕರು ಮತ್ತು ಕೃತಿಗಳು.',nearestLiteraryMilestones:'ಈ ವರ್ಷಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ದಾಖಲೆ ಇಲ್ಲ; ಸಮೀಪದ ಸಾಹಿತ್ಯ ಮೈಲಿಗಲ್ಲುಗಳನ್ನು ತೋರಿಸಲಾಗಿದೆ.'})
Object.assign(messages.en,{literaryTimeline:'Literary timeline',activeLiteraryMilestones:'Poets, authors and works associated with kingdoms active in this year.',nearestLiteraryMilestones:'No work is yet recorded for an active kingdom in this year; showing the nearest literary milestones.'})
Object.assign(messages.kn,{visibleThisYear:'ಈ ವರ್ಷದಲ್ಲಿ ಕಾಣುವ ತಾಣಗಳು',allHeritageShown:'ಎಲ್ಲ ದಿನಾಂಕಗಳ ತಾಣಗಳು',showAllHeritage:'ಕಾಲರೇಖೆಯ ವರ್ಷವನ್ನು ಮೀರಿ ಎಲ್ಲ ತಾಣಗಳನ್ನು ತೋರಿಸಿ',showAllInscriptions:'ಎಲ್ಲ ಶಾಸನಗಳನ್ನು ತೋರಿಸಿ',publicReviewNote:'ಪರಿಶೀಲನೆ ಬಾಕಿ ದಾಖಲೆಗಳು ಸಾರ್ವಜನಿಕವಾಗಿ ಗೋಚರಿಸುತ್ತವೆ',appearLater:'ನಂತರ ಕಾಣುವವು',awaitingDate:'ದಿನಾಂಕಕ್ಕಾಗಿ ಕಾಯುತ್ತಿವೆ',timelineAppearance:'ಕಾಲರೇಖೆಯಲ್ಲಿ ಆರಂಭ'})
Object.assign(messages.en,{visibleThisYear:'sites visible this year',allHeritageShown:'all dated and undated sites',showAllHeritage:'Show all sites regardless of timeline year',showAllInscriptions:'Show all inscriptions',publicReviewNote:'Pending-review records remain visible to the public',appearLater:'appear later',awaitingDate:'awaiting a date',timelineAppearance:'Timeline start'})
messages.kn.checkStatusLabels={verified:'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',matched:'ಹೊಂದಾಣಿಕೆಯಾಗಿದೆ',identified:'ಗುರುತಿಸಲಾಗಿದೆ',pending:'ಬಾಕಿಯಿದೆ','not-provided':'ಒದಗಿಸಿಲ್ಲ','not-found-in-linked-registers':'ಜೋಡಿಸಿದ ಪಟ್ಟಿಗಳಲ್ಲಿ ಕಂಡಿಲ್ಲ',unresolved:'ಇನ್ನೂ ಪರಿಹಾರವಾಗಿಲ್ಲ'}
messages.en.checkStatusLabels={verified:'verified',matched:'matched',identified:'identified',pending:'pending','not-provided':'not provided','not-found-in-linked-registers':'not found in linked registers',unresolved:'unresolved'}

Object.assign(messages.kn,{literaryWork:'ಸಾಹಿತ್ಯ ಕೃತಿ',creator:'ಕರ್ತೃ',language:'ಭಾಷೆ',script:'ಲಿಪಿ',datePrecision:'ದಿನಾಂಕ ನಿಖರತೆ',associatedKingdom:'ಸಂಬಂಧಿತ ರಾಜ್ಯ',mappedPlace:'ನಕ್ಷೆಯ ಸ್ಥಳ',externalResources:'ಬಾಹ್ಯ ಸಂಪನ್ಮೂಲಗಳು',inscriptionTimeline:'ಶಾಸನ ಕಾಲರೇಖೆ',activeInscriptionMilestones:'ಆಯ್ದ ವರ್ಷದ ಸಮೀಪದ ನಕ್ಷೆಗೊಳಿಸಿದ ಶಾಸನಗಳು.'})
Object.assign(messages.en,{literaryWork:'Literary work',creator:'Creator',language:'Language',script:'Script',datePrecision:'Date precision',associatedKingdom:'Associated kingdom',mappedPlace:'Mapped place',externalResources:'External resources',inscriptionTimeline:'Inscription timeline',activeInscriptionMilestones:'Mapped inscriptions nearest to the selected year.'})
Object.assign(messages.kn,{itemEdition:'ಪ್ರತ್ಯೇಕ ಶಾಸನ ಪ್ರಕಟಣೆ',presentCondition:'ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ',inscriptionConditionLabels:{'incomplete-sheltered':'ಅಪೂರ್ಣ · ಆಶ್ರಯದಲ್ಲಿ ಸಂರಕ್ಷಿಸಲಾಗಿದೆ','good-sheltered':'ಉತ್ತಮ ಸ್ಥಿತಿ · ಆಶ್ರಯದಲ್ಲಿ ಸಂರಕ್ಷಿಸಲಾಗಿದೆ','very-good-sheltered':'ಅತ್ಯುತ್ತಮ ಸ್ಥಿತಿ · ಆಶ್ರಯದಲ್ಲಿ ಸಂರಕ್ಷಿಸಲಾಗಿದೆ','intact-in-situ':'ಮೂಲಸ್ಥಳದಲ್ಲಿ ಸುಸ್ಥಿತಿಯಲ್ಲಿದೆ','worn-in-situ':'ಮೂಲಸ್ಥಳದಲ್ಲಿ ಸವೆದಿದೆ','condition-unresolved':'ಸ್ಥಿತಿ ನಿರ್ಧಾರವಾಗಿಲ್ಲ'}})
Object.assign(messages.en,{itemEdition:'Item-level edition',presentCondition:'Present condition',inscriptionConditionLabels:{'incomplete-sheltered':'Incomplete · sheltered','good-sheltered':'Good · sheltered','very-good-sheltered':'Very good · sheltered','intact-in-situ':'Intact in situ','worn-in-situ':'Worn in situ','condition-unresolved':'Condition unresolved'}})
Object.assign(messages.kn,{searchAtlas:'ಎಲ್ಲ ಐತಿಹಾಸಿಕ ದಾಖಲೆಗಳನ್ನು ಹುಡುಕಿ',searchAtlasPlaceholder:'ರಾಜ್ಯ, ಕವಿ, ಕೃತಿ, ಶಾಸನ, ಸ್ಥಳ…',researchFilters:'ಸಂಶೋಧನಾ ಶೋಧಕಗಳು',recordType:'ದಾಖಲೆ ವಿಧ',allRecordTypes:'ಎಲ್ಲ ದಾಖಲೆ ವಿಧಗಳು',century:'ಶತಮಾನ',allCenturies:'ಎಲ್ಲ ಶತಮಾನಗಳು',allKingdoms:'ಎಲ್ಲ ರಾಜ್ಯಗಳು',allLanguages:'ಎಲ್ಲ ಭಾಷೆಗಳು',allScripts:'ಎಲ್ಲ ಲಿಪಿಗಳು',reviewStatus:'ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ',allReviewStatuses:'ಎಲ್ಲ ಸ್ಥಿತಿಗಳು',clearFilters:'ಶೋಧಕಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',searchResults:'ಫಲಿತಾಂಶಗಳು',noSearchResults:'ಹೊಂದುವ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',searchKinds:{polity:'ರಾಜ್ಯ',person:'ವ್ಯಕ್ತಿ',work:'ಸಾಹಿತ್ಯ ಕೃತಿ',inscription:'ಶಾಸನ',event:'ಐತಿಹಾಸಿಕ ಘಟನೆ',culture:'ಸಂಸ್ಕೃತಿ ಮತ್ತು ಸ್ಮಾರಕ',place:'ಸ್ಥಳ',heritage:'ಪರಂಪರೆ ಅಭ್ಯರ್ಥಿ',districtHistory:'ಜಿಲ್ಲಾ ಸಮಗ್ರ ಇತಿಹಾಸ',templeSites:'ದೇವಾಲಯ ತಾಣಗಳು'}})
Object.assign(messages.en,{searchAtlas:'Search all historical records',searchAtlasPlaceholder:'Kingdom, poet, work, inscription, place…',researchFilters:'Research filters',recordType:'Record type',allRecordTypes:'All record types',century:'Century',allCenturies:'All centuries',allKingdoms:'All kingdoms',allLanguages:'All languages',allScripts:'All scripts',reviewStatus:'Review status',allReviewStatuses:'All statuses',clearFilters:'Clear filters',searchResults:'results',noSearchResults:'No matching records found.',searchKinds:{polity:'Kingdom',person:'Person',work:'Literary work',inscription:'Inscription',event:'Historical event',culture:'Culture and monument',place:'Place',heritage:'Heritage candidate',districtHistory:'District deep history',templeSites:'Temple sites'}})
Object.assign(messages.kn,{inscriptionAuditTitle:'ಜಿಲ್ಲಾವಾರು ಶಾಸನ ಪರಿಶೀಲನೆ',inscriptionAuditIntro:'ಎಲ್ಲ 31 ಜಿಲ್ಲೆಗಳ ಮೊದಲ ಹಂತದ ಪರಿಶೀಲನೆ ಪೂರ್ಣವಾಗಿದೆ: ನಕ್ಷೆಗೊಳಿಸಿದ ದಾಖಲೆಗಳು ಅಥವಾ ಆಕರ-ಗುರುತಿಸಿದ ಆದ್ಯತಾ ಅಭ್ಯರ್ಥಿಗಳು ಪ್ರತಿಯೊಂದು ಜಿಲ್ಲೆಗೂ ಲಭ್ಯವಿವೆ.',districtsSeeded:'ಜಿಲ್ಲೆಗಳಲ್ಲಿ ಆರಂಭಿಕ ದಾಖಲೆಗಳು',candidateIdentified:'ಆದ್ಯತಾ ಅಭ್ಯರ್ಥಿ ಗುರುತಿಸಲಾಗಿದೆ',priorityCandidates:'ಆದ್ಯತಾ ಅಭ್ಯರ್ಥಿಗಳು',corpusLocated:'ಆಕರದಲ್ಲಿ ಗುರುತಿಸಲಾಗಿದೆ',openCandidateSource:'ಆಕರ ತೆರೆಯಿರಿ ↗',inscriptionResearchGap:'ಈ ಜಿಲ್ಲೆಗೆ ಇನ್ನೂ ಶಾಸನ ದಾಖಲೆ ಅಥವಾ ಆಕರ-ಗುರುತಿಸಿದ ಅಭ್ಯರ್ಥಿ ಸೇರಿಸಿಲ್ಲ.'})
Object.assign(messages.en,{inscriptionAuditTitle:'District-by-district inscription audit',inscriptionAuditIntro:'First-pass assessment is complete across all 31 districts: every district now has either mapped records or a source-located priority candidate.',districtsSeeded:'districts seeded',candidateIdentified:'Priority candidate identified',priorityCandidates:'priority candidates',corpusLocated:'Source located',openCandidateSource:'Open source ↗',inscriptionResearchGap:'No inscription record or source-located candidate has yet been added for this district.'})
Object.assign(messages.kn,{personProfile:'ವ್ಯಕ್ತಿ ಪರಿಚಯ',personEvidenceIntro:'ಈ ಪರಿಚಯವು ಪ್ರತ್ಯೇಕವಾಗಿ ಪರಿಶೀಲಿಸಿದ ಘಟನೆಗಳು, ಆಳ್ವಿಕೆ ಅವಧಿಗಳು, ಕೃತಿಗಳು ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ದಾಖಲೆಗಳನ್ನು ಒಟ್ಟುಗೂಡಿಸುತ್ತದೆ. ಪ್ರತಿ ಕೊಂಡಿಯ ಆಕರ ಮತ್ತು review ಸ್ಥಿತಿಯನ್ನು ಅದರ ವಿವರದಲ್ಲಿ ನೋಡಬಹುದು.',linkedContributions:'ಸಂಬಂಧಿತ ದಾಖಲೆಗಳು',contributionTypes:'ಕೊಡುಗೆ ವಿಭಾಗಗಳು',historicalEvents:'ಐತಿಹಾಸಿಕ ಘಟನೆಗಳು',reignsAndPeriods:'ಆಳ್ವಿಕೆ ಮತ್ತು ರಾಜಕೀಯ ಅವಧಿಗಳು',literaryWorks:'ಸಾಹಿತ್ಯ ಕೃತಿಗಳು',cultureAndMonuments:'ಕಲೆ, ಸಂಸ್ಕೃತಿ ಮತ್ತು ಸ್ಮಾರಕಗಳು',roles:'ಪಾತ್ರಗಳು',personSources:'ವ್ಯಕ್ತಿಯ ನೇರ ಆಕರಗಳು',inheritedEvidenceNote:'ಈ ವ್ಯಕ್ತಿಯ ಕೊಡುಗೆಗಳಿಗೆ ಆಕರಗಳು ಸಂಬಂಧಿತ ಘಟನೆ, ಕೃತಿ, ಸ್ಮಾರಕ ಅಥವಾ ಆಳ್ವಿಕೆ ದಾಖಲೆಯಲ್ಲಿವೆ; ವ್ಯಕ್ತಿಯ ಜೀವನಚರಿತ್ರೆಗೆ ಪ್ರತ್ಯೇಕ ಆಕರ ಪರಿಶೀಲನೆ ಇನ್ನೂ ಬಾಕಿಯಿದೆ.',noLinkedContributions:'ಈ ವ್ಯಕ್ತಿಗೆ ಇನ್ನೂ ದಿನಾಂಕಿತ ಕೊಡುಗೆ ದಾಖಲೆ ಜೋಡಿಸಲ್ಪಟ್ಟಿಲ್ಲ.',personRoleLabels:{ruler:'ಅರಸು / ಆಡಳಿತಗಾರ',patron:'ಆಶ್ರಯದಾತ',poet:'ಕವಿ',author:'ಲೇಖಕ'}})
Object.assign(messages.en,{personProfile:'Person profile',personEvidenceIntro:'This profile brings together separately reviewed events, reigns, works and cultural records. Open any link to inspect its sources and review status.',linkedContributions:'linked records',contributionTypes:'contribution categories',historicalEvents:'Historical events',reignsAndPeriods:'Reigns and political periods',literaryWorks:'Literary works',cultureAndMonuments:'Art, culture and monuments',roles:'Roles',personSources:'Direct person sources',inheritedEvidenceNote:'Evidence for these contributions is carried by the linked event, work, monument or reign record; a separate biographical source review is still pending.',noLinkedContributions:'No dated contribution record is linked to this person yet.',personRoleLabels:{ruler:'Ruler',patron:'Patron',poet:'Poet',author:'Author'}})

Object.assign(messages.kn,{bce:'ಕ್ರಿ.ಪೂ.',researchCandidate:'ಸಂಶೋಧನಾ ಅಭ್ಯರ್ಥಿ · ಇನ್ನೂ ಪ್ರಕಟಿಸಿಲ್ಲ',bceResearchTitle:'ಕ್ರಿ.ಪೂ. ಕಾಲದ ಸಾಕ್ಷ್ಯ ಅನ್ವೇಷಣೆ',noPublishedPolity:'ಈ ವರ್ಷಕ್ಕೆ ಇನ್ನೂ ಪರಿಶೀಲಿಸಿ ಪ್ರಕಟಿಸಿದ ರಾಜಕೀಯ ಭೂಪ್ರದೇಶದ ದಾಖಲೆ ಇಲ್ಲ.',bceResearchNote:'ಆಕರ-ಗುರುತಿಸಿದ ಅಭ್ಯರ್ಥಿಗಳನ್ನು ಕಾಲರೇಖೆಯಲ್ಲಿ ತೋರಿಸಲಾಗಿದೆ. ಸ್ಥಳಕ್ಕೆ ತಾತ್ಕಾಲಿಕ ನಿರ್ದೇಶಾಂಕ ದೊರೆತಿದ್ದರೆ ಕಿತ್ತಳೆ ಬಣ್ಣದ ತುಂಡು-ಗೆರೆಯ ವೃತ್ತದಲ್ಲಿ ಕಾಣುತ್ತದೆ; ಇದು ಪರಿಶೀಲಿತ ತಾಣ ಅಥವಾ ರಾಜಕೀಯ ಗಡಿ ಅಲ್ಲ.',openEpigraphy:'ಶಾಸನ ಅನ್ವೇಷಣೆ ತೆರೆಯಿರಿ',mapResearchCandidates:'ಪರಿಶೀಲನೆ ಬಾಕಿ ತಾಣಗಳು',researchLegend:'ಕಿತ್ತಳೆ ತುಂಡು-ಗೆರೆ · ಪರಿಶೀಲನೆ ಬಾಕಿ',pendingHumanReview:'ಮಾನವ ಪರಿಶೀಲನೆ ಬಾಕಿ · ಕಿತ್ತಳೆ ತುಂಡು-ಗೆರೆ ಗುರುತು',coordinatePrecision:'ನಿರ್ದೇಶಾಂಕ ನಿಖರತೆ',openEvidenceWorkflow:'ಸಾಕ್ಷ್ಯ ಕಾರ್ಯವಿಧಾನ ತೆರೆಯಿರಿ'})
Object.assign(messages.en,{bce:'BCE',researchCandidate:'Research candidate · not yet published',bceResearchTitle:'BCE evidence exploration',noPublishedPolity:'No reviewed and published political-territory record is available for this year yet.',bceResearchNote:'Source-located candidates appear on the timeline. Where a provisional coordinate exists, an amber dashed ring marks it as an unverified location—not a verified site or political boundary.',openEpigraphy:'Open Epigraphy Explorer',mapResearchCandidates:'Pending-review sites',researchLegend:'Amber dashed · pending review',pendingHumanReview:'Needs human review · amber dashed marker',coordinatePrecision:'Coordinate precision',openEvidenceWorkflow:'Open evidence workflow'})

export const getInitialLocale = () => localStorage.getItem('karnataka-atlas-locale') || 'kn'
export const setStoredLocale = locale => localStorage.setItem('karnataka-atlas-locale',locale)
