import { useEffect, useMemo, useRef, useState } from 'react'
import { CircleMarker, GeoJSON, MapContainer, Popup, TileLayer, useMap } from 'react-leaflet'
import { atlasData } from './data/atlas'
import SourceLink from './SourceLink'

const primary=(value,locale)=>value?.[locale]||value?.en||value?.kn||''
const secondary=(value,locale)=>value?.[locale==='kn'?'en':'kn']||''
const placeById=new Map(atlasData.places.map(item=>[item.id,item]))
const polityById=new Map([...atlasData.polities,...atlasData.externalPolities].map(item=>[item.id,item]))
const sourceById=new Map(atlasData.sources.map(item=>[item.id,item]))
const reviewedStatuses=new Set(['reviewed','verified','published'])
const roleColors={queen:'#a43d72',patron:'#a43d72','community-hero':'#a83e32',defender:'#a83e32','resistance-leader':'#a83e32','resistance-fighter':'#a83e32','community-leader':'#b06a1f',artisan:'#537a42',washerman:'#537a42',boatman:'#16867a','vachana-poet':'#8b5aa5','religious-figure':'#8b5aa5',explorer:'#16867a',traveller:'#16867a',scholar:'#355fa8',administrator:'#657084','military-leader':'#703e82',soldier:'#703e82',lieutenant:'#703e82',ruler:'#315f91','foreign-monarch':'#315f91',poet:'#8b5aa5',author:'#355fa8',diplomat:'#4361ee'}
const roleLabel={
  kn:{ruler:'ಅರಸು / ಆಡಳಿತಗಾರ',queen:'ರಾಣಿ',patron:'ಆಶ್ರಯದಾತ',poet:'ಕವಿ',author:'ಲೇಖಕ','vachana-poet':'ವಚನಕಾರ',scholar:'ವಿದ್ವಾಂಸ',administrator:'ಆಡಳಿತಗಾರ','military-leader':'ಸೇನಾನಾಯಕ',diplomat:'ರಾಜತಾಂತ್ರಿಕ',explorer:'ಅನ್ವೇಷಕ / ಪ್ರವಾಸಿಗ',traveller:'ಪ್ರವಾಸಿಗ','foreign-monarch':'ವಿದೇಶಿ ರಾಜ','community-hero':'ಜನಸಮುದಾಯದ ವೀರ ವ್ಯಕ್ತಿ','community-leader':'ಜನನಾಯಕ',defender:'ರಕ್ಷಕ','resistance-leader':'ಪ್ರತಿರೋಧ ನಾಯಕ','resistance-fighter':'ಪ್ರತಿರೋಧ ಹೋರಾಟಗಾರ',lieutenant:'ಸೇನಾಧಿಕಾರಿ',soldier:'ಸೈನಿಕ',artisan:'ಕಾಯಕಜೀವಿ',washerman:'ಮಡಿವಾಳ',boatman:'ಅಂಬಿಗ','religious-figure':'ಧಾರ್ಮಿಕ ವ್ಯಕ್ತಿ'},
  en:{ruler:'Ruler',queen:'Queen',patron:'Patron',poet:'Poet',author:'Author','vachana-poet':'Vachana poet',scholar:'Scholar',administrator:'Administrator','military-leader':'Military leader',diplomat:'Diplomat',explorer:'Explorer / traveller',traveller:'Traveller','foreign-monarch':'Foreign monarch','community-hero':'Community hero','community-leader':'Community leader',defender:'Defender','resistance-leader':'Resistance leader','resistance-fighter':'Resistance fighter',lieutenant:'Lieutenant',soldier:'Soldier',artisan:'Artisan',washerman:'Washerman',boatman:'Boatman','religious-figure':'Religious figure'},
}
const copy={
  kn:{title:'ವ್ಯಕ್ತಿಗಳ ಅನ್ವೇಷಣೆ',intro:'ಅರಸರು ಮತ್ತು ರಾಣಿಯರ ಜೊತೆಗೆ ಕವಿಗಳು, ವಿದ್ವಾಂಸರು, ಯೋಧರು, ಕಾಯಕಜೀವಿಗಳು, ಪ್ರವಾಸಿಗರು ಮತ್ತು ಜನಸಮುದಾಯದ ಪ್ರಮುಖ ವ್ಯಕ್ತಿಗಳನ್ನು ಅವರ ಕಾಲ, ಸ್ಥಳ, ಕೃತಿ ಮತ್ತು ಸಾಕ್ಷ್ಯಗಳೊಂದಿಗೆ ಅನ್ವೇಷಿಸಿ.',search:'ಕನ್ನಡ ಅಥವಾ ಇಂಗ್ಲಿಷ್ ಹೆಸರನ್ನು ಹುಡುಕಿ',allRoles:'ಎಲ್ಲ ಪಾತ್ರಗಳು / ವೃತ್ತಿಗಳು',allPolities:'ಎಲ್ಲ ರಾಜ್ಯಗಳು ಮತ್ತು ಸಂದರ್ಭಗಳು',allCenturies:'ಎಲ್ಲ ಶತಮಾನಗಳು',allDistricts:'ಎಲ್ಲ ಜಿಲ್ಲೆಗಳು',allGenders:'ಎಲ್ಲ ಲಿಂಗ ದಾಖಲೆಗಳು',women:'ಮಹಿಳೆಯರು',genderUnrecorded:'ಲಿಂಗ ದಾಖಲಾಗಿಲ್ಲ',allReviews:'ಎಲ್ಲ ಪರಿಶೀಲನಾ ಸ್ಥಿತಿಗಳು',results:'ವ್ಯಕ್ತಿಗಳು',mapped:'ನಕ್ಷೆಗೊಳಿಸಿದವರು',reviewed:'ಪರಿಶೀಲಿತರು',clear:'ಶೋಧಕಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',mapTitle:'ವ್ಯಕ್ತಿಗಳು ಮತ್ತು ಸಂಬಂಧಿತ ಸ್ಥಳಗಳು',mapNote:'ಗುರುತನ್ನು ಆಯ್ಕೆಮಾಡಿ; ತುಂಡು-ಗೆರೆ ವೃತ್ತವು ಪರಿಶೀಲನೆ ಬಾಕಿ ದಾಖಲೆಯನ್ನು ಸೂಚಿಸುತ್ತದೆ. ಒಂದೇ ಸ್ಥಳದ ಗುರುತುಗಳನ್ನು ಆಯ್ಕೆಗಾಗಿ ಸ್ವಲ್ಪ ಬೇರ್ಪಡಿಸಲಾಗಿದೆ.',modern:'ಆಧುನಿಕ',historical:'ಐತಿಹಾಸಿಕ ಕಾಗದ',timeline:'ವ್ಯಕ್ತಿಗಳ ಕಾಲರೇಖೆ',undated:'ದಿನಾಂಕ ಇನ್ನೂ ನಿರ್ಧರಿಸಿಲ್ಲ',profile:'ವ್ಯಕ್ತಿ ಪರಿಚಯ',roles:'ಪಾತ್ರಗಳು / ವೃತ್ತಿಗಳು',polity:'ರಾಜ್ಯ / ಐತಿಹಾಸಿಕ ಸಂದರ್ಭ',district:'ಸಂಬಂಧಿತ ಜಿಲ್ಲೆ',gender:'ಲಿಂಗ ದಾಖಲೆ',woman:'ಮಹಿಳೆ',notRecorded:'ದಾಖಲಾಗಿಲ್ಲ',dates:'ಜೀವನ / ಚಟುವಟಿಕೆ ಅವಧಿ',review:'ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ',contributions:'ಸಂಬಂಧಿತ ದಾಖಲೆಗಳು',events:'ಘಟನೆಗಳು',works:'ಸಾಹಿತ್ಯ ಕೃತಿಗಳು',culture:'ಕಲೆ, ಸಂಸ್ಕೃತಿ ಮತ್ತು ಸ್ಮಾರಕಗಳು',reigns:'ಆಳ್ವಿಕೆ ಅವಧಿಗಳು',relations:'ರಾಜಕೀಯ ಮತ್ತು ಜಾಗತಿಕ ಸಂಬಂಧಗಳು',inscriptions:'ಶಾಸನಗಳು',sources:'ನೇರ ಆಕರಗಳು',openAtlas:'ಮುಖ್ಯ ಭೂಪಟದಲ್ಲಿ ತೆರೆಯಿರಿ',close:'ವಿವರ ಮುಚ್ಚಿ',noResults:'ಈ ಶೋಧಕಗಳಿಗೆ ಹೊಂದುವ ವ್ಯಕ್ತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',districtDerived:'ಸಂಬಂಧಿತ ನಕ್ಷೆ ಬಿಂದುವಿನಿಂದ ಜಿಲ್ಲೆಯನ್ನು ಲೆಕ್ಕಿಸಲಾಗಿದೆ.',unknownPlace:'ನಕ್ಷೆ ಸ್ಥಳ ಇನ್ನೂ ಜೋಡಿಸಿಲ್ಲ.'},
  en:{title:'People Explorer',intro:'Explore rulers and queens alongside poets, scholars, soldiers, working people, travellers and community figures through their periods, places, works and evidence.',search:'Search Kannada or English names',allRoles:'All roles / professions',allPolities:'All polities and contexts',allCenturies:'All centuries',allDistricts:'All districts',allGenders:'All gender records',women:'Women',genderUnrecorded:'Gender not recorded',allReviews:'All review statuses',results:'people',mapped:'mapped',reviewed:'reviewed',clear:'Clear filters',mapTitle:'People and associated places',mapNote:'Select a marker; a dashed circle identifies a record awaiting review. Markers sharing one place are slightly separated for selection.',modern:'Modern',historical:'Historical paper',timeline:'People timeline',undated:'Date not yet established',profile:'Person profile',roles:'Roles / professions',polity:'Polity / historical context',district:'Associated district',gender:'Gender record',woman:'Woman',notRecorded:'Not recorded',dates:'Life / activity period',review:'Review status',contributions:'Linked records',events:'Events',works:'Literary works',culture:'Art, culture and monuments',reigns:'Reign periods',relations:'Political and global relations',inscriptions:'Inscriptions',sources:'Direct sources',openAtlas:'Open in main atlas',close:'Close profile',noResults:'No people match these filters.',districtDerived:'District is calculated from an associated mapped point.',unknownPlace:'No mapped location is linked yet.'},
}

const dateYear=date=>date?.era==='BCE'?-Number(date.from):Number(date?.from)
const centuryKey=year=>Number.isFinite(year)&&year!==0?`${year<0?'BCE':'CE'}-${Math.floor((Math.abs(year)-1)/100)+1}`:null
const centuryLabel=(key,locale)=>{const [era,value]=key.split('-'),number=Number(value),suffix=number%10===1&&number%100!==11?'st':number%10===2&&number%100!==12?'nd':number%10===3&&number%100!==13?'rd':'th';return locale==='kn'?`${value}ನೇ ಶತಮಾನ ${era==='BCE'?'ಕ್ರಿ.ಪೂ.':'ಕ್ರಿ.ಶ.'}`:`${value}${suffix} century ${era}`}
const dateLabel=(date,locale)=>{
  if(!Number.isFinite(date?.from))return copy[locale].undated
  const era=date.era==='BCE'?(locale==='kn'?'ಕ್ರಿ.ಪೂ.':'BCE'):(locale==='kn'?'ಕ್ರಿ.ಶ.':'CE')
  const prefix=date.precision==='circa'?(locale==='kn'?'ಸು. ':'c. '):''
  return `${prefix}${date.from}${date.to!==date.from?`–${date.to}`:''} ${era}`
}
const recordDate=record=>record?.date
const validPoint=point=>Array.isArray(point)&&point.length===2&&point.every(Number.isFinite)
const placePoint=id=>{const coordinates=placeById.get(id)?.location?.coordinates;return coordinates&&validPoint(coordinates)?[coordinates[1],coordinates[0]]:null}
const relationPoints=relation=>{
  const geography=relation.geography||{}
  return [geography.origin?.coordinates,geography.destination?.coordinates].filter(validPoint).map(([lng,lat])=>[lat,lng])
}
const ringContains=(ring,[lat,lng])=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if(((yi>lat)!==(yj>lat))&&(lng<(xj-xi)*(lat-yi)/(yj-yi)+xi))inside=!inside}return inside}
const geometryContains=(geometry,point)=>{if(!geometry)return false;const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.type==='MultiPolygon'?geometry.coordinates:[];return polygons.some(polygon=>polygon[0]&&ringContains(polygon[0],point))}
const roleColor=person=>(person.roles||[]).map(role=>roleColors[role]).find(Boolean)||'#b26a22'

function PeopleMapViewport({points,selectedPoint}){
  const map=useMap()
  const pointKey=points.map(point=>point.join(',')).join('|')
  useEffect(()=>{if(selectedPoint)map.setView(selectedPoint,8,{animate:true});else if(points.length>1)map.fitBounds(points,{padding:[32,32],maxZoom:7});else if(points[0])map.setView(points[0],7)},[map,pointKey,selectedPoint?.[0],selectedPoint?.[1]])
  return null
}

export default function PeopleExplorer({locale='kn',districtGeojson,mapTheme='modern',setMapTheme,onOpenAtlas}){
  const t=copy[locale]
  const [query,setQuery]=useState('')
  const [role,setRole]=useState('all')
  const [polity,setPolity]=useState('all')
  const [century,setCentury]=useState('all')
  const [district,setDistrict]=useState('all')
  const [gender,setGender]=useState('all')
  const [review,setReview]=useState('all')
  const initialPersonId=new URLSearchParams(window.location.search).get('person')
  const [selectedId,setSelectedId]=useState(()=>atlasData.people.some(item=>item.id===initialPersonId)?initialPersonId:null)
  const timelineRef=useRef(null)

  const records=useMemo(()=>{const base=atlasData.people.map(person=>{
    const events=atlasData.events.filter(item=>(item.peopleIds||[]).includes(person.id))
    const works=atlasData.works.filter(item=>(item.creatorIds||[]).includes(person.id))
    const culture=atlasData.culturalHeritage.filter(item=>(item.peopleIds||[]).includes(person.id))
    const reigns=atlasData.reigns.filter(item=>(item.rulerIds||[]).includes(person.id))
    const relations=atlasData.politicalRelations.filter(item=>(item.peopleIds||[]).includes(person.id))
    const inscriptions=atlasData.inscriptions.filter(item=>(item.peopleIds||[]).includes(person.id))
    const polityRecord=polityById.get(person.polityId)
    const points=[...events.map(item=>item.location?.coordinates&&[item.location.coordinates[1],item.location.coordinates[0]]),...culture.flatMap(item=>(item.placeIds||[]).map(placePoint)),...inscriptions.map(item=>placePoint(item.placeId)),...relations.flatMap(relationPoints),placePoint(polityRecord?.capitalId)].filter(validPoint)
    const dated=[person.date,...events.map(recordDate),...works.map(recordDate),...culture.map(recordDate),...reigns.map(recordDate),...relations.map(recordDate),...inscriptions.map(recordDate)].filter(date=>Number.isFinite(date?.from)).sort((a,b)=>dateYear(a)-dateYear(b))
    const timelineDate=Number.isFinite(person.date?.from)?person.date:dated[0]||person.date
    const anchor=points[0]||null
    const districtFeature=anchor&&districtGeojson?.features?.find(feature=>geometryContains(feature.geometry,anchor))
    return {...person,polity:polityRecord,points,anchor,timelineDate,timelineYear:dateYear(timelineDate),districtId:districtFeature?.properties?.id||null,districtName:primary(districtFeature?.properties?.districtName,locale)||districtFeature?.properties?.district||null,gender:person.gender||'unrecorded',contributions:{events,works,culture,reigns,relations,inscriptions}}
  });const shared=new Map();return base.map(person=>{if(!person.anchor)return person;const key=person.anchor.map(value=>value.toFixed(4)).join(',');const index=shared.get(key)||0;shared.set(key,index+1);if(index===0)return{...person,mapAnchor:person.anchor};const ring=Math.ceil(index/8),angle=(index%8)/8*Math.PI*2,radius=.055*ring;return{...person,mapAnchor:[person.anchor[0]+Math.sin(angle)*radius,person.anchor[1]+Math.cos(angle)*radius]}})},[districtGeojson,locale])
  const roles=useMemo(()=>[...new Set(records.flatMap(person=>person.roles||[]))].sort((a,b)=>(roleLabel[locale][a]||a).localeCompare(roleLabel[locale][b]||b,locale)),[records,locale])
  const polities=useMemo(()=>[...new Map(records.map(person=>person.polity).filter(Boolean).map(item=>[item.id,item])).values()].sort((a,b)=>primary(a.name,locale).localeCompare(primary(b.name,locale),locale)),[records,locale])
  const centuries=useMemo(()=>[...new Set(records.map(person=>centuryKey(person.timelineYear)).filter(Boolean))].sort((a,b)=>{const [eraA,valueA]=a.split('-'),[eraB,valueB]=b.split('-');const yearA=eraA==='BCE'?-Number(valueA)*100:Number(valueA)*100,yearB=eraB==='BCE'?-Number(valueB)*100:Number(valueB)*100;return yearA-yearB}),[records])
  const districts=useMemo(()=>[...new Map(records.filter(person=>person.districtId).map(person=>[person.districtId,person.districtName])).entries()].sort((a,b)=>String(a[1]).localeCompare(String(b[1]),locale)),[records,locale])
  const reviews=useMemo(()=>[...new Set(records.map(person=>person.review?.status).filter(Boolean))].sort(),[records])
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return records.filter(person=>{
    const personCentury=centuryKey(person.timelineYear)
    const searchText=`${primary(person.name,'kn')} ${primary(person.name,'en')} ${(person.roles||[]).join(' ')} ${primary(person.polity?.name,'kn')} ${primary(person.polity?.name,'en')}`.toLowerCase()
    return (!needle||searchText.includes(needle))&&(role==='all'||person.roles.includes(role))&&(polity==='all'||person.polityId===polity)&&(century==='all'||personCentury===century)&&(district==='all'||person.districtId===district)&&(gender==='all'||person.gender===gender)&&(review==='all'||person.review?.status===review)
  }).sort((a,b)=>(Number.isFinite(a.timelineYear)?a.timelineYear:Infinity)-(Number.isFinite(b.timelineYear)?b.timelineYear:Infinity)||primary(a.name,locale).localeCompare(primary(b.name,locale),locale))},[records,query,role,polity,century,district,gender,review,locale])
  const selected=records.find(person=>person.id===selectedId)||null
  const mapped=filtered.filter(person=>person.mapAnchor)
  const choosePerson=person=>{setSelectedId(person.id);const url=new URL(window.location.href);url.searchParams.set('person',person.id);history.replaceState(null,'',`${url.pathname}${url.search}#people`)}
  const closePerson=()=>{setSelectedId(null);const url=new URL(window.location.href);url.searchParams.delete('person');history.replaceState(null,'',`${url.pathname}${url.search}#people`)}
  const clearFilters=()=>{setQuery('');setRole('all');setPolity('all');setCentury('all');setDistrict('all');setGender('all');setReview('all')}
  const onTimelineKeyDown=event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;const buttons=[...timelineRef.current.querySelectorAll('button')];const index=buttons.indexOf(event.target);if(index<0)return;event.preventDefault();const direction=event.key==='ArrowLeft'||event.key==='ArrowUp'?-1:1;buttons[(index+direction+buttons.length)%buttons.length]?.focus()}
  const contributionGroups=selected?[['events',t.events,selected.contributions.events],['works',t.works,selected.contributions.works],['culture',t.culture,selected.contributions.culture],['reigns',t.reigns,selected.contributions.reigns],['relations',t.relations,selected.contributions.relations],['inscriptions',t.inscriptions,selected.contributions.inscriptions]].filter(([, ,items])=>items.length):[]
  return <main className="portal-page people-page" id="people">
    <section className="people-hero"><div><p className="eyebrow">{t.profile}</p><h2>{t.title}</h2><p>{t.intro}</p></div><div className="people-stats"><span><b>{filtered.length}</b>{t.results}</span><span><b>{mapped.length}</b>{t.mapped}</span><span><b>{filtered.filter(person=>reviewedStatuses.has(person.review?.status)).length}</b>{t.reviewed}</span></div></section>
    <section className="people-filters" aria-label={t.title}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.search} aria-label={t.search}/><select value={role} onChange={event=>setRole(event.target.value)} aria-label={t.roles}><option value="all">{t.allRoles}</option>{roles.map(value=><option key={value} value={value}>{roleLabel[locale][value]||value}</option>)}</select><select value={polity} onChange={event=>setPolity(event.target.value)} aria-label={t.polity}><option value="all">{t.allPolities}</option>{polities.map(item=><option key={item.id} value={item.id}>{primary(item.name,locale)}</option>)}</select><select value={century} onChange={event=>setCentury(event.target.value)} aria-label={t.allCenturies}><option value="all">{t.allCenturies}</option>{centuries.map(value=><option key={value} value={value}>{centuryLabel(value,locale)}</option>)}</select><select value={district} onChange={event=>setDistrict(event.target.value)} aria-label={t.district}><option value="all">{t.allDistricts}</option>{districts.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><select value={gender} onChange={event=>setGender(event.target.value)} aria-label={t.gender}><option value="all">{t.allGenders}</option><option value="woman">{t.women}</option><option value="unrecorded">{t.genderUnrecorded}</option></select><select value={review} onChange={event=>setReview(event.target.value)} aria-label={t.review}><option value="all">{t.allReviews}</option>{reviews.map(value=><option key={value}>{value}</option>)}</select><button type="button" onClick={clearFilters}>{t.clear}</button></section>
    <section className={`people-explorer-layout ${selected?'has-profile':''}`}>
      <section className={`people-map theme-${mapTheme}`}><div className="people-map-heading"><div><strong>{t.mapTitle}</strong><small>{t.mapNote}</small></div><div role="group" aria-label={t.mapTitle}><button className={mapTheme==='modern'?'active':''} onClick={()=>setMapTheme('modern')}>{t.modern}</button><button className={mapTheme==='historical'?'active':''} onClick={()=>setMapTheme('historical')}>{t.historical}</button></div></div><MapContainer center={[14.7,76.2]} zoom={6} minZoom={3} scrollWheelZoom><PeopleMapViewport points={mapped.map(person=>person.mapAnchor)} selectedPoint={selected?.mapAnchor}/><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{districtGeojson&&<GeoJSON data={districtGeojson} interactive={false} style={{color:'#68738b',weight:1,fillColor:'#4361ee',fillOpacity:.025,dashArray:'5 4'}}/>}{mapped.map(person=><CircleMarker key={person.id} center={person.mapAnchor} radius={selected?.id===person.id?9:6} pathOptions={{color:person.review?.status==='needs-review'?'#b06a1f':'#fff',fillColor:roleColor(person),fillOpacity:.9,weight:selected?.id===person.id?4:2,dashArray:person.review?.status==='needs-review'?'4 3':null}} eventHandlers={{click:()=>choosePerson(person)}}><Popup><strong>{primary(person.name,locale)}</strong><br/><span>{secondary(person.name,locale)}</span><br/><small>{person.roles.map(value=>roleLabel[locale][value]||value).join(' · ')}</small><br/><button type="button" onClick={()=>choosePerson(person)}>{t.profile}</button></Popup></CircleMarker>)}</MapContainer></section>
      <section className="people-directory"><div className="people-directory-head"><strong>{filtered.length} {t.results}</strong><small>{districts.length?`${t.districtDerived}`:''}</small></div><div className="people-grid">{filtered.map(person=><button type="button" className={selected?.id===person.id?'selected':''} key={person.id} onClick={()=>choosePerson(person)}><i style={{background:roleColor(person)}}></i><span><strong>{primary(person.name,locale)}</strong><small>{secondary(person.name,locale)}</small><em>{person.roles.slice(0,3).map(value=>roleLabel[locale][value]||value).join(' · ')}</em><b>{dateLabel(person.timelineDate,locale)} · {primary(person.polity?.name,locale)||'—'}</b></span><mark className={person.review?.status}>{person.review?.status}</mark></button>)}{!filtered.length&&<p className="people-empty">{t.noResults}</p>}</div></section>
      {selected&&<aside className="people-profile"><button className="people-close" onClick={closePerson} aria-label={t.close}>×</button><p className="eyebrow">{t.profile}</p><h3>{primary(selected.name,locale)}</h3><p className="entity-secondary">{secondary(selected.name,locale)}</p><div className="people-role-tags">{selected.roles.map(value=><span key={value} style={{'--role-color':roleColors[value]||'#657084'}}>{roleLabel[locale][value]||value}</span>)}</div><dl><div><dt>{t.dates}</dt><dd>{dateLabel(selected.timelineDate,locale)}</dd></div><div><dt>{t.polity}</dt><dd>{primary(selected.polity?.name,locale)||'—'}<small>{secondary(selected.polity?.name,locale)}</small></dd></div><div><dt>{t.district}</dt><dd>{selected.districtName||t.unknownPlace}</dd></div><div><dt>{t.gender}</dt><dd>{selected.gender==='woman'?t.woman:t.notRecorded}</dd></div><div><dt>{t.review}</dt><dd><span className={`review-badge ${selected.review?.status}`}>{selected.review?.status}</span></dd></div></dl><h4>{t.contributions}</h4>{contributionGroups.length?<div className="people-contributions">{contributionGroups.map(([key,label,items])=><section key={key}><strong>{label} · {items.length}</strong>{items.slice(0,6).map(item=><span key={item.id}><b>{primary(item.name,locale)}</b><small>{dateLabel(item.date,locale)}</small></span>)}</section>)}</div>:<p>{t.unknownPlace}</p>}<h4>{t.sources}</h4><div className="people-sources">{(selected.citations||[]).map((citation,index)=>{const source=sourceById.get(citation.sourceId);return <p key={`${citation.sourceId}-${index}`}>{source?.url?<SourceLink href={source.url} label={primary(source.title,locale)||citation.sourceId} locale={locale}/>:<strong>{primary(source?.title,locale)||citation.sourceId}</strong>}<small>{citation.locator}</small></p>})}</div><button className="people-open-atlas" type="button" onClick={()=>onOpenAtlas(selected)}>{t.openAtlas}</button></aside>}
    </section>
    <section className="people-timeline"><div><strong>{t.timeline}</strong><small>{filtered.filter(person=>Number.isFinite(person.timelineYear)).length} / {filtered.length}</small></div><div ref={timelineRef} onKeyDown={onTimelineKeyDown}>{filtered.filter(person=>Number.isFinite(person.timelineYear)).map(person=><button type="button" key={person.id} className={selected?.id===person.id?'selected':''} onClick={()=>choosePerson(person)}><time>{dateLabel(person.timelineDate,locale)}</time><strong>{primary(person.name,locale)}</strong><small>{person.roles.slice(0,2).map(value=>roleLabel[locale][value]||value).join(' · ')}</small></button>)}</div></section>
  </main>
}
